# Name of the quickstart (required)
name: Errors Inbox with Jira

# Displayed in the UI (required)
title: Errors Inbox with Jira

# Long-form description of the quickstart (required)
description: |
  [Errors Inbox](https://newrelic.com/blog/how-to-relic/errors-inbox-with-jira) is an error-tracking solution included with New Relic One’s Full Stack Observability license, including the free tier. Errors Inbox tracks the errors that New Relic is already monitoring, groups them together, and displays them on a single screen allowing engineers to ​​proactively catch and fix errors before they escalate.   
  Now, you can integrate Errors Inbox to Jira, so you can continue to work and collaborate in the tools you’re already using. With this integration you can:

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  How to integrate Jira with New Relic Errors Inbox

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Joseph Counts
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - jira
  - error
  - inbox
  - newrelic

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:

documentation:
  - name: How to Docs
    url: https://newrelic.com/blog/how-to-relic/errors-inbox-with-jira
    description: How to integrate Jira with New Relic Errors Inbox

# Content / Design
logo: logo.png
website: https://www.newrelic.com
