name: video-android
title: Video agent for Android.
description: Agent to monitor video applications for Android.
summary: Agent to monitor video applications for Android.
level: Community
authors:
  - New Relic
keywords:
  - nrlabs
  - nrlabs-data
  - video
  - tracking
  - Android
documentation:
  - name: Video Android. Installation Docs
    url: https://github.com/newrelic/video-agent-android
    description: Agent to monitor video applications for Android.
icon: icon.svg
logo: logo.svg