
# Name of the quickstart
slug: lampy-stack

# Title of the quickstart
title: LAMPy stack

summary: |
  Monitor your apps using New Relic’s LAMPy integration with Linux, Apache, MySQL and Python agents for infrastructure, web server, database, and application monitoring.
# Description of the quickstart
description: |
 ## Comprehensive LAMPy stack monitoring system:
  LAMPy is a free, open source software stack used for building web sites and applications. LAMPy is an acronym for the operating system (Linux), the webserver (Apache), the database server (MySQL), and the programming language (Python).
  ## What should you look for in a LAMPy dashboard?
  - Linux: CPU Usage, total memory usage, disk usage, etc
  - Apache: requests per second, bytes per second, workers status, etc
  - MySQL: operations per second, InnoDB read & writes, etc
  - Python: throughput, transaction overview, WSGI, etc
  - You are also free to create your own chart by using the stored metrics
  ## What’s included in the LAMPy quickstart?
  This quickstart includes the following preconfigured observability solutions:
  - Application metrics with your server’s primary health metrics, like CPU usage, memory, disk usage and more
  - Multiple high-value alerts including latest number of questions per second, error transactions percentage, memory usage and CPU utilization
  - Informative dashboards (Busy worker status, Operations, InnoDB read and write, etc)

# The logo of the quickstart
icon: logo.png

# Support level
level: New Relic

# Authors of the quickstart
authors:
  - New Relic
  - Ramana Reddy

installPlans:
  - apache-integration
  - mysql-integration
  - setup-python-agent

keywords:
  - LAMPy
  - linux
  - apache
  - mysql
  - python

dashboards:
  - lampy
alertPolicies:
  - lampy

documentation:
  - name: LAMPy stack integration documentation
    description: |
      Integrate your LAMPy app and get your data into New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/lampy-integration/

dataSourceIds:
  - lampy-stack
