id: deeper-network

displayName: Deeper Network

description: |
  ## Deeper Connect Monitoring Quickstart

  Get deep visibility into the health, performance, connections, logs and balance of your Deeper Connect device.

  Alert and identify potential issues, or simply use for remote monitoring.

logo: logo.png

install:
  primary:
    nerdlet: nr1-install-newrelic.quickstart-installation-plan
    nerdletState:
      quickstart_id: b5feb1f0-ca9f-4f31-92fc-f6e117ef91bb
  requiresAccount: true
  secondary:
    link: https://github.com/Kav91/deeper-connect-monitoring

keywords:
  - infrastructure
  - network
  - nrlabs
  - deeper-network
  - crypto
  - security

categoryTerms:
  - newrelic partner
  - network
  - infrastructure
