
# Name of the pack
name: Kafka

# Description of the pack
description: |+
  Official New Relic pack for Kafka
  Use this pack together with the New Relic Kafka On Host Integration to get insight into the performance of your Kafka cluster.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://kafka.apache.org/

# Authors of the pack
authors:
  - New Relic
  - Jakub Kotkowiak

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: kafka
