id: lighttpd
displayName: Lighttpd
description: |
  ## Comprehensive monitoring for your lighttpd server

  Lighttpd is an open-source web server designed for high-performance situations while staying standards-compliant, secure, and adaptable.

  ### Why monitor your lighttpd server?

  Lighttpd monitoring provides important information to help you construct a complete picture of your web server's performance. This performance data includes uptime, network in bytes and packets, number of connections, and more.

  ### What’s included?

  When you monitor your lighttpd server with New Relic, you get immediate full-stack observability, including:
  - Be alerted on things like average number of connections, average number of requests and high memory usage.
  - Use dashboards to monitor crucial performance metrics, such as uptime, connection state handle request, connection state still alive, networks, requests per second, and more.

icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/lighttpd-integration/

keywords:
  - lighttpd
  - web server
categoryTerms:
  - newrelic
