
slug: reactjs

description: |
  ## Comprehensive monitoring quickstart for ReactJS
  ReactJS helps you build browser-rendered HTML, CSS and javascript applications easily. Manage asynchronous data and routing right out of the box with our quickstart dashboards.

  ## Why monitor ReactJS?
  The monitor allows us to know what issues customers are having in real time and provides an intuitive way to understand those issues, and direct those issues to the proper party for resolution.


  ## What’s included in this quickstart?
  New Relic's ReactJS monitoring quickstart boasts instant full-stack observability out-of-the-box:
  - Easy to use performance monitoring dashboards.
  - See all your JavaScript errors tagged by deployment.
  - Get a detailed view of your web application traffic, including page views, load times, sessions, and most popular content.

summary: |
  Instrument and monitor your ReactJS build apps with our Vue browser monitoring agent. Analyze performance data right out of the box.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Phaneendra Kosanam
title: ReactJS
documentation:
  - name: ReactJS installation docs
    description: |
      Integrate your ReactJS app with our browser monitoring and get your data into New Relic.
    url: >-
      https://docs.newrelic.com/

installPlans:
  - reactjs
dashboards:
  - reactjs
alertPolicies:
  - reactjs
# Keywords for filtering / searching criteria in the UI
keywords:
  - ReactJS
  - JavaScript
  - Frontend
  - Browser Monitoring
