id: e709396f-5b37-4e9c-a302-e872c9b864fd
slug: jfrog-platform
title: JFrog Platform
description: |
  ## Why monitor JFrog Platform

  The JFrog Platform is a leading universal end-to-end DevOps platform for automating, managing, securing, distributing, orchestrating, monitoring, and optimizing your Cl/ CD pipeline. These different elements of the JFrog platform need to be monitored in order for the enterprise to know in real-time about the health, performance and security of the DevOps supply chain.

  ### JFrog Platform quickstart highlights

  The integration will surface Platform Logs, Xray Violations data and system performance data available through Open Metrics, as pre-built dashboards within a JFrog Platform application made available within the New Relic One Programmable Observability platform.

  - Monitor the JFrog platform in your familiar and convenient New Relic One Programmable Observability platform
  - Pre-built JFrog dashboards depicting critical logs and metrics from the JFrog platform
  - Utilizes FluentD, an open source and one of the most lightweight log processors and forwarders in the market
summary: |
  FluentD-based custom log forwarder for the JFrog platform for customers using New Relic's observability platform
level: Verified
authors:
  - JFrog
  - Mahitha Byreddy
keywords:
  - newrelic
  - newrelic partner
  - apm
  - open source monitoring
documentation:
  - name: JFrog Observability Solution
    url: https://github.com/jfrog/log-analytics-newrelic
    description: |
      JFrog Github documentation
icon: icon.svg
dashboards:
  - jfrog-artifactory
  - jfrog-xray
installPlans:
  - third-party-jfrog-platform
dataSourceIds:
  - jfrog-platform
