id: synthetics-private-locations
displayName: Synthetics private locations dashboard example
description: Get started monitoring your private locations with a best practices dashboard.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/monitor-private-locations/
