id: 01fdea36-5a15-44b4-a864-c4c99866735b
name: node-js
description: |-
  ## What is Node.js?

  Node.js is an open-source, cross-platform, back-end, JavaScript runtime
  environment that executes JavaScript code outside a web browser.


  ## Get started!

  Leverage community expertise and instantly get value out of your telemetry data. This quickstart automatically instruments Node.js with the New Relic Node.js agent, and allows you to instantly monitor your Node application with out-of-the-box dashboards and alerts. Further leverage New Relic's APM capabilities by setting up [errors inbox](https://docs.newrelic.com/docs/apm/apm-ui-pages/errors-inbox/errors-inbox/), [transaction tracing](https://docs.newrelic.com/docs/apm/transactions/transaction-traces/introduction-transaction-traces/), and [service maps](https://docs.newrelic.com/docs/understand-dependencies/understand-system-dependencies/service-maps/introduction-service-maps/).

  ## More info

  Check out the [documentation](https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/introduction-new-relic-nodejs/) to learn more about New Relic monitoring for Node.js.
summary: |-
  Monitor Node.js with New Relic's Node.js agent
icon: icon.svg
logo: logo.svg
level: Community
authors:
  - New Relic
  - Emil Hammarstrand
title: Node.js
documentation:
  - name: Node.js installation docs
    description: |
      Node.js is an open-source, cross-platform, back-end, JavaScript runtime
      environment that executes JavaScript code outside a web browser.
    url: >-
      https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent
keywords:
  - apm
  - node.js
  - language agent

installPlans:
  - node-agent
