id: a4383e84-ad92-4771-8f58-d0a459542be0
slug: calico-newrelic
title: Calico (Prometheus)

description: |
  Calico is an open source networking and network security solution for containers, virtual machines, and native host-based workloads. Calico supports a broad range of platforms including Kubernetes, OpenShift, Mirantis Kubernetes Engine (MKE), OpenStack, and bare metal services.Whether you opt to use Calico's eBPF data plane or Linux’s standard networking pipeline, Calico delivers blazing fast performance with true cloud-native scalability

  This quickstart is based on metrics sent to New Relic using Prometheus Agent or Prometheus Server.

summary: |
   A curated dashboard based on Prometheus metrics which helps you understand the Calico CNI of your k8s cluster.This quickstart is based on metrics sent to New Relic using Prometheus Agent or Prometheus Server.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Ragalahari Potti

# Keywords for filtering / searching criteria in the UI
keywords:
  - calico
  - kubernetes
  - k8s
  - prometheus
  - remote-write
  - cni

installPlans:
  - setup-prometheus
  - setup-prometheus-agent-mode

# Documentation references
documentation:
 - name: Prometheus installation docs
   description: |
     Use Prometheus remote_write or Prometheus Agent
   url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic
- name: Calico Integration Docs
  name: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/calico-integration/
- name: Calico Metrics Documentation
  description: |
    Calico Metrics Documentation
  url: https://projectcalico.docs.tigera.io/reference/felix/prometheus

icon: logo.png
website: https://projectcalico.docs.tigera.io/

dashboards:
  - calico

alertPolicies:
  - calico
