id: bitbucket
displayName: Bitbucket
description: |
  ## Atlassian Bitbucket integration


  ### About Bitbucket


  With best-in-class Jira integration, and built-in CI/CD, Bitbucket Cloud is
  the native Git tool in Atlassian’s Open DevOps solution.


  ### About this integration


  This integration is built around a [Bitbucket
  Pipe](https://bitbucket.org/product/features/pipelines/integrations). This
  tool will enable you to send CI/CD events into New Relic, where you can
  monitor your Bitbucket Pipelines. 


  With this integration you can monitor:
    - Number of events/pipeline builds
    - Track priority events
    - Real time event log from your pipeline
    - Events and priority events over time
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: fdc99da8-0061-4c5f-bd90-ef67a8b2419f
      requiresAccount: true
  fallback:
    link:
      url: https://bitbucket.org/product/features/pipelines/integrations
keywords:
  - newrelic partner
  - devops
  - bitbucket
  - atlassian
  - cicd
  - featured
  - pipes
  - pipline
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
