id: third-party-biztalk360
displayName: BizTalk360
description: |
  With BizTalk360 quickstart, you get some of the important performance metrics of BizTalk environments in your New Relic dashboard.

icon: logo.png
install:
  primary:
    link:
      url: https://docs.biztalk360.com/docs/new-relic-integration
keywords:
  - biztalk360
  - integration
  - biztalk server
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
