id: d465bf08-b737-4bc5-b5ad-dd5be272967b

name: postman

title: Postman

description: |
  ## Postman Introduction

  Postman is an API platform for building and using APIs. Postman simplifies each step of the API lifecycle and
  streamlines collaboration so you can create better APIs—faster.

  ## Postman quickstart highlights

  The Postman quickstart allows you to get an opinionated visualization of your Postman API data within minutes.

  - View your average latency over time
  - Compare your total request count over time
  - Get a real time tally of recent errors and failed tests
  - Measure API 4xx and 5xx failures
  - Review your byte traffic over time

summary: |
  Integrate Postman with New Relic to monitor your API performance effectively.

level: Community

authors:
  - Shashank Awasthi
  - Postman

keywords:
  - api
  - postman
  - newrelic partner
  - featured

installPlans:
  - third-party-postman

documentation:
  - name: Installation Docs
    url: https://learning.postman.com/docs/integrations/available-integrations/new-relic/
    description: Postman integration configuration

logo: logo.svg
website: https://www.postman.com/
