slug: aws-mediapackagevod
description: |-
  ## What is AWS MediaPackage VOD?

  Zero-administration compute platform for back-end web developers that runs your code for you in AWS cloud.


  ### Get started!

  Start monitoring AWS MediaPackage VOD by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS MediaPackage VOD documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elemental-mediapackage-vod-monitoring-integration/) to learn more about New Relic monitoring for AWS MediaPackage VOD.
summary: |-
  Monitor AWS MediaPackage VOD by connecting AWS to New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: AWS MediaPackage VOD 
documentation:
  - name: AWS MediaPackage VOD installation docs
    description: |
      Monitor AWS MediaPackage VOD by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elemental-mediapackage-vod-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - mediapackage
  - elemental
dashboards:
  - aws-mediapackagevod
  installPlans:
  - aws-cloudwatch-metric-streams
