slug: aws-elemental-mediapackage
description: |-
  ## What is AWS Elemental MediaPackage?

  Zero-administration compute platform for back-end web developers that runs your code for you in AWS cloud.


  ### Get started!

  Start monitoring AWS Elemental MediaPackage by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS Elemental MediaPackage documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elemental-mediapackage-vod-monitoring-integration/) to learn more about New Relic monitoring for AWS Elemental MediaPackage.
summary: |-
  Monitor AWS Elemental MediaPackage by connecting AWS to New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: AWS Elemental MediaPackage
documentation:
  - name: AWS Elemental MediaPackage installation docs
    description: |
      Monitor AWS Elemental MediaPackage by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elemental-mediapackage-vod-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - mediapackage
  - elemental
dashboards:
  - aws-elemental-mediapackage
  installPlans:
  - aws-cloudwatch-metric-streams
