

slug: blazor
description: |
  ## Comprehensive monitoring quickstart for Blazor

  Microsoft developed Blazor to build web UIs with C#, HTML, and CSS. As a feature of ASP.NET, our Blazor integration with the .NET agent lets you monitor your apps with our quickstart dashboards right out of the box.


  ## Why monitor Blazor?

  Blazor offers a lot of useful features in addition to allowing C# developers to utilize their preferred language for web development. Blazor allows you to run your code through WebAssembly on the server or the client, and you can decide which users or devices experience each method.
  
  There are a few compelling arguments that support the employment of Blazor:
  - All of the major browsers support WebAssembly.
  - Using C# for interactive web apps.
  - Utilize current C# libraries.
  - Near-native performance.
  - Debugging and tooling.

  ## What’s included in this quickstart?

  Get these Blazor monitoring features out of the box with our quickstart:
  - Understand the health of your system with dashboards that show throughput and error rate data, logs, web transaction time, Apdex score, and more. 
  - Alerts ()
  - Monitor scripts and functions.
  - Monitor web transactions.

summary: |
  Instrument and monitor your Blazor-built app with our .NET agent. Analyze your performance data right out of the box. 
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: Blazor
documentation:
  - name: Blazor installation docs
    description: |
      Instrument and monitor your Blazor-built app with our .NET agent. Analyze your performance data right out of the box. 
    url: >- 
      https://docs.newrelic.com/
keywords:  
  - apm
  - dotnet
  - .net
  - blazor
  - c-sharp
  - c#
installPlans:
  - dotnet-agent
dashboards:
  - dotnet
alertPolicies:
  - dotnet
