id: f2143fb1-5504-4850-8620-06e9341858ea
name: codestream
description: |
  ## What is CodeStream?

  CodeStream helps dev teams discuss, review, and understand code.

  ### Get started!

  CodeStream supercharges development workflows by putting collaboration tools in your IDE. It supports pull requests from GitHub, BitBucket and GitLab, issue management from Jira, Trello, Asana and 9 others, and provides code discussion that ties it all together, integrated with Slack, MS Teams, email, and in-editor notifications.

  ### More info

  Check out the [documentation](https://docs.codestream.com)
summary: |
  View production telemetry and troubleshoot errors from your IDE
icon: icon.svg
logo: logo.svg
level: New Relic
authors:
  - New Relic
title: CodeStream
documentation:
  - name: CodeStream installation docs
    description: View production telemetry and troubleshoot errors from your IDE
    url: >-
      https://docs.codestream.com
