id: f2143fb1-5504-4850-8620-06e9341858ea
name: new-relic-codestream

description: |
  ## What is New Relic CodeStream?

  New Relic CodeStream helps dev teams discuss, review, and understand code.

  ### Get started!

  New Relic CodeStream supercharges development workflows by putting collaboration tools in your IDE. It supports pull requests from GitHub, BitBucket and GitLab, issue management from Jira, Trello, Asana and 9 others, observability from New Relic One and Pixie, and provides code discussion that ties it all together, integrated with Slack, MS Teams, email, and in-editor notifications.

  With the New Relic One integration:
  - Click from Errors Inbox right to the code that caused it in your IDE
  - Step through stack-traces and method calls, navigating to specific lines of code
  - Add production logging on the fly, and see the results, without leaving your editor
  - Discover recent errors assigned to you, assign errors, and update their status 
  - View telemetry such as error rate, throughput and executions/sec for a given method

  Install the extension for [VS Code](https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream-vs), and all [JetBrains](https://plugins.jetbrains.com/plugin/12206-codestream-github-gitlab-bitbucket-prs-and-code-review) editors.
  
  ### More info

  Check out the [documentation](https://docs.codestream.com)
summary: |
  View production telemetry and troubleshoot errors from your IDE
icon: icon.png
logo: logo.svg
level: New Relic
authors:
  - New Relic
title: New Relic CodeStream
documentation:
  - name: Installation Docs
    description: View production telemetry and troubleshoot errors from your IDE
    url: https://docs.codestream.com
  - name: New Relic CodeStream Demo
    description: See New Relic CodeStream in action
    url: https://codestream.com/demo
website: https://codestream.com
