id: azure-infrastructure-monitoring
displayName: Azure Infrastructure monitoring
description: |
  Azure Infrastructure monitoring allows monitoring of various Azure services.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations/
