id: openai
displayName: OpenAI
description: |
  A lightweight tool to monitor your OpenAI workload.
icon: logo.png
install:
  primary:
    link:
      url: https://github.com/newrelic/openai-api-monitoring

