
# Name of the pack (required)
name: trendmicro-cloudone-conformity

title: New Relic’s integration with Trend Micro Cloud One - Conformity

# Description of the pack (required)
description: >-
  New Relic’s integration with Trend Micro Cloud One - Conformity ingests cloud security posture management (CSPM)
  data from Conformity into New Relic in real-time. 
  The integration deploys a Amazon Web Services (AWS) CloudFormation stack in your AWS account. 
Bring your Conformity generated CSPM data into New Relic one to contextualize and correlate it with workload telemetry data, delivering AI powered visualizations and quick insights.
  Conformity generated CSPM data into New Relic One where it's contextualized and correlated with workload telemetry data 
  delivering AI powered visualizations and quick insights.

# Support level: New Relic | Verified | Community (required)
level: Community

# Design
icon: icon.png
logo: logo.png
website: https://www.trendmicro.com/en_us/partners/alliance-partners/explore-alliance-partners/new-relic.html

# Authors of the pack (required)
authors:
  - Rohit Kaul

documentation:
  - name: GitHub repository
    url: https://github.com/newrelic-experimental/newrelic-connector-trendmicro-cloud-one-conformity#readme
  - name: New Relic blog post
    url: https://newrelic.com/blog/how-to-relic/trend-micro-aws
  - name: Trend Micro blog post
    url: https://www.trendmicro.com/en_us/devops/21/f/how-to-achieve-more-security-observability.html
