# Name of the quickstart (required)
name: postman

# Displayed in the UI (required)
title: Postman

# Long-form description of the quickstart (required)
description: |
  Observe the performance of your APIs using Postman and New Relic

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Observe the performance of your APIs using Postman and New Relic

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Shashank Awasthi

# Keywords for filtering / searching criteria in the UI
keywords:
  - api
  - Postman

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - infra-agent-standard

documentation:
  - name: Installation Docs
    url: https://learning.postman.com/docs/integrations/available-integrations/new-relic/
    description: Integration configuration on Postman

# Content / Design
logo: logo.svg
website: https://www.postman.com/
