# Name of the quickstart (required)
name: postman

# Displayed in the UI (required)
title: Postman

# Long-form description of the quickstart (required)
description:|
  ## Postman's New Relic Integration

  Postman is an API platform that allows you to manage your APIs throught it's lifecycle. Postman's
  integration with NewRelic allows you to observe the performance of your APIs by sending results from Postman monitor
  run to NewRelic and getting key API performance information back in Postman's API platform

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Integrate Postman with New Relic to monitor your API performance effectively.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Shashank Awasthi

# Keywords for filtering / searching criteria in the UI
keywords:
  - api
  - postman

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - third-party-postman

documentation:
  - name: Installation Docs
    url: https://learning.postman.com/docs/integrations/available-integrations/new-relic/
    description: Postman integration configuration

# Content / Design
logo: logo.svg
website: https://www.postman.com/
