id: blazor-server
displayName: Blazor Server
description: Instrument and monitor your Blazor Server application with our .NET APM agent. Analyze your performance data right out of the box.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework/#technologies
icon: logo.png
