id: otel-gitlab-integration
displayName: Gitlab
description: |
  GitLab is a popular single application for the entire DevOps lifecycle, fulfilling all the fundamentals for CI/CD in one environment.
icon: logo.svg
install:
  primary:
    link:
      url: https://www.newrelic.com
keywords:
  - gitlab
  - opentelemetry
  - otel
  - pipelines
categoryTerms:
  - open source monitoring

