id: otel-gitlab-integration
displayName: Gitlab
description: |
  GitLab is a popular single application for the entire DevOps lifecycle, fulfilling all the fundamentals for CI/CD in one environment.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 980ab07a-3483-4b44-bbac-ed9c0a9a41a1
      requiresAccount: true
  fallback:
    link:
      url: https://github.com/newrelic-experimental/gitlab
keywords:
  - gitlab
  - opentelemetry
  - otel
  - pipelines
categoryTerms:
  - open source monitoring
