id: aws-polly
displayName: AWS Polly
description: |
  AWS Polly Machine Learning Services
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-polly
icon: logo.png
