id: battlesnake
displayName: Battlesnake
description: |
  ## About Battlesnake

    Battlesnake is a multi-player programming game played by developers all over the world. All you need to play is a live web server that implements the Battlesnake API.

  ## About this quickstart

  [Battlesnake](https://play.battlesnake.com/) is a multi-player programming game played by developers all over the world. All you need to play is a live web server that implements the [Battlesnake API](https://docs.battlesnake.com/).

  With New Relic, you can monitor you Battlesnake [server](https://docs.newrelic.com/docs/infrastructure/infrastructure-monitoring/get-started/get-started-infrastructure-monitoring/) and [web application](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/introduction-apm). This quickstart includes a few helpful dashboards to ensure your server is compliant with the game's server requirements and your Battlesnake is set up for success!

  Additional features coming soon!
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 63a65857-a25e-4654-9174-928e5894b3b9
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/apm-report-custom-events-attributes/
keywords:
  - game
  - infrastructure
  - snake
  - battlesnake
categoryTerms:
  - newrelic partner
