id: 

slug: flink
description: |
  ## Comprehensive monitoring quickstart for Flink
  New Relic detects your Flink metrics like job manager (checkpoints, direct, mapped, metaspace memory usage),
  task manager (shuffle netty, operators), heap memory usage and more.

  ## Why monitor Flink?
  An ideal Flink Performance Monitoring provides an easy way for effective monitoring and alerting of your Flink jobs


  ## What’s included in this quickstart?
  New Relic's Flink monitoring quickstart boasts instant full-stack observability out-of-the-box:
  - High value alerts for your Apache Flink (errors,usage metrics and JVM)
  - Easy to use performance monitoring dashboards 
  - Custom alerts that proactively inform developers about the status of their Flink Jobs.


summary: |
  New Relic’s instant observability quickstart with Flink monitoring helps to detect client, jobmanager and taskmanager logs and parses them into a JSON payload.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Flink
documentation:
  - name: Flink integration documentation
    description: |
      New Relic’s instant observability quickstart with Flink monitoring helps to detect client, jobmanager and taskmanager logs and parses them into a JSON payload.
    url: >-
      https://docs.newrelic.com/
keywords:
  - apache flin
installPlans:
  - flink
dashboards:
  - flink
alertPolicies:
  - flink
