id: c377d781-da77-4dd6-b5a8-6a25a39e2582

# Name of the quickstart (required)
name: ansible

# Displayed in the UI (required)
title: Ansible

# Long-form description of the quickstart (required)
description: |
  Open-source software provisioning, configuration management, and
  application-deployment tool enabling infrastructure as code.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Open-source software provisioning, configuration management, and
  application-deployment tool enabling infrastructure as code.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - automation
  - devops
  - sre
  - gitops

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
documentation:
  - name: Ansible installation docs
    description: |
      Open-source software provisioning, configuration management, and
      application-deployment tool enabling infrastructure as code.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/config-management-tools/configure-new-relic-infrastructure-using-ansible
  - name: Ansible Galaxy
    description: |
      Ansible Galaxy page for the New Relic Ansible role
    url: >-
      https://galaxy.ansible.com/newrelic/newrelic_agents

# Content / Design
logo: logo.svg
website: https://galaxy.ansible.com/newrelic/newrelic_agents
