id: lampy-stack
displayName: LAMPy Stack Integration
description: |
  This LAMPy quickstart allows you to monitor a LAMPy stack ( Linux, Apache,MySQL, Python). The LAMPy stack quickstart allows you to monitor metrics and understand the status of your application. It includes a specific dashboard to get observability for an entire LAMPy stack.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/
icon: logo.png

keywords:
  - LAMPy
  - Linux
  - Apache
  - MySQL
  - Python