id: lampy-stack
displayName: LAMPy Stack Integration
description: |
  Monitor your apps using New Relic’s LAMPy integration with Linux, Apache, MySQL and Python agents for infrastructure, web server, database, and application monitoring.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/lampy-integration/
icon: logo.png

keywords:
  - LAMPy
  - Linux
  - Apache
  - MySQL
  - Python