id: newrelic-java-rmi
displayName: RMI Java Agent Extension
description: |
  RMI Java agent extension that effectively links client-initiated calls with remote server calls, facilitating the monitoring of these interactions. 
  Once deployed, the client and server transactions will be tied together with Distributed Tracing.
install:
  primary:
    link:
      url: https://github.com/newrelic/newrelic-java-rmi
icon: logo.svg
