id: 71419258-a96f-4845-b4f7-723f3b29d6a5

# Name of the pack
name: infrastructure

# Title of the pack
title: Infrastructure

# Description of the pack
description: |
  The infrastructure pack allows you to get visibilility into the performance and availability of your hosts and operating system.
  
summary: |
  New Relic's instant observability quickstart includes custom views, alerts, and multiple customizable dashboards to identify and resolve errors quickly and enhance user experience.

# Support level
level: New Relic

# Authors of the pack
authors:
  - New Relic
  - Darren Doyle
installPlans:
  - guided-install
