# Name of the quickstart (required)
name: newrelic-ingest-metric

# Displayed in the UI (required)
title: New Relic Ingest Metric

# Long-form description of the quickstart (required)
description: |
  This quickstart provides a script to generate a custom metric for capturing New Relic One ingest, split by data type and faceted by the attributes of your choice. The script is configured via synthetic monitor. The quickstart also includes a dashboard to analyze ingest by data type and faceted attribute.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Custom metric for capturing detailed data ingest

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Nora Shannon Johnson!

# Keywords for filtering / searching criteria in the UI
keywords:
  - ingest
  - ingestion
  - custom metric
  - synthetic monitor
  - consumption
  - billing
  - facet

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - infra-agent-standard

documentation:
  - name: nr1-ingest-metric-script (github)
    url: https://github.com/umanorapracadadia/nr1-ingest-metric-script
    description: Instructions for updating and activating the synthetic monitor that generates the newrelic.ingest custom metric

# Content / Design
logo: logo.png
website: https://www.newrelic.com
