id: 4a2bc392-e39d-423d-a771-ef09dff5a4c2
# Name of the quickstart (required)
name: pixie-quickstart

# Displayed in the UI (required)
title: Pixie Quickstart

# Long-form description of the quickstart (required)
description: |
  The Pixie quickstart includes a dashboard providing Latency, Errors, and Throughput observability for your Pixie services as well as example alert conditions.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Pixie quickstart for Latency, Errors, and Throughput observability.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Brad Schmitt
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - pixie
  - kubernetes
  - errors
  - latency
  - throughput
  - ebpf

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - kubernetes-install

# Content / Design
icon: pixie-icon-color.png
logo: pixie-horizontal-color.png
website: https://www.newrelic.com
