# Name of the quickstart (required)
name: Delphix

# Displayed in the UI (required)
title: Delphix

# Long-form description of the quickstart (required)
description: |
  This Delphix quickstart allows you to get visibility into all your Delphix Virtualization platforms. Use this quickstart together with this [integration](https://github.com/delphix/dct-newrelic-integration) 

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Monitor Delphix Virtualization operations with New Relic.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Diego Loureda
  - Carlos Cuellar

# Keywords for filtering / searching criteria in the UI
keywords:
  - delphix
  - dct
  - vdb
  - dsource
  - "data control tower"

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - delphix

documentation:
  - name: Installation Docs
    url: https://github.com/delphix/dct-newrelic-integration
    description: Description about this doc reference
