id: 98f77308-4ac3-4c55-bc56-eb9d12f52ab7
# Name of the quickstart (required)
slug: delphix

# Displayed in the UI (required)
title: Delphix

# Long-form description of the quickstart (required)
description: |
  ### Summary
  
  The Delphix quickstart for New Relic allows administrators to gain insights and observability of the Delphix DevOps Data Platform. Users can monitor various Delphix objects, such as dSources and VDBs, and trigger alerts on exceeded thresholds. 

  In addition, when leveraging the Delphix integration, users can feed data into triggered New Relic workflows to command data-ready RCA environments through a [ServiceNow automated request](https://store.servicenow.com/sn_appstore_store.do#!/store/application/bb688f9f9734111012b7318c1253af11) or direct webhook.

  ### What's the value?
 
  The Delphix DevOps Data Platform is a powerful test data management tool enabling the provisioning of RCA environments for mission-critical applications on demand. The quickstart allows Delphix administrators to monitor their usage, maintain high availability, and reduce the costs of forgotten virtual databases. 

  Site Reliability Engineers rely on Delphix and New Relic to provide mission-critical application environments within minutes of an issue which eases investigation during stressful issues and helps achieve SLA times. Delphix can reduce provisioning times from days to minutes.

  ### What's inside?
  
  The quickstart contains a sample Delphix Continuous Data dashboard and Storage Utilization Alert to help users get started. 
  
  Populating data for dashboards, alerts, and workflows requires the [Delphix Integration](https://github.com/delphix/dct-newrelic-integration) and [Delphix Data Control Tower](https://docs.delphix.com/dct).

icon: logo.png

website: https://www.delphix.com

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Monitor and observe the Delphix DevOps Data Platform and responsed to mission-critical application issues with data-ready RCA environments.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Diego Loureda
  - Carlos Cuellar
  - Nick Mathison

# Keywords for filtering / searching criteria in the UI
keywords:
  - delphix
  - newrelic partner
  - devops
  - test data management
  - database
  - sre

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - third-party-delphix

documentation:
  - name: Quickstart and Integration Documentation
    url: https://github.com/delphix/dct-newrelic-integration
    description: Complete documentation to install and configure the Delphix quickstart and integration.

dashboards:
  - delphix-dashboard
alertPolicies:
  - delphix
