# todo boom what is this?
id: d0e829a6-ede4-4933-9065-9f0c56f8aa7e

# Name of the quickstart (required)
name: mlops-monalabs

# Displayed in the UI
title: Mona Labs

# Long-form description of the quickstart (required)
# todo boom youval for this.
description: |
  Algorithmia Insights provides tools for deploying your machine-learning models into production. By integrating, Algorithmia's integration with New Relic, you'll be able to instrument, analyze, troubleshoot, and optimize your machine-learning performance across your entire system. By rigorously observing your capabilities, you'll be able to react quickly to changes in the model's input or output and the relationship between the two.

  Send your model performance metrics from Algorithmia Insights to New Relic and you'll have real-time monitoring for your algorithms. You'll explore your metrics data with user-friendly charts and learn the state of your algorithms at a glance for faster and more efficient troubleshooting.

# todo boom youval for this.
# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Algorithmia's integration with New Relic will allow you to instrument, analyze, troubleshoot, and optimize your machine-learning performance across your entire system.

# todo boom
# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Mona Labs

# todo boom ask itai if he has something.
# Keywords for filtering / searching criteria in the UI
keywords:
  - mlops
  - ml
  - ai
  - mona
  - machine-learning
  - machine learning

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - monalabs-mlops

documentation:
  - name: Mona Labs Docs
    # todo boom we need the link from them.
    url: https://docs.newrelic.com/docs/integrations/mlops-integrations/algorithmia-mlops-integration/
    description: Documentation on the workings of the Mona Labs integration

# Content / Design
logo: logo.png
website: https://monalabs.io/
