id: mobile-network-performance-install

displayName: Mobile Network Performance

description: |
  This guide details how to use and instrument mobile application and install dashboard to monitor your application on mobile devices with New Relic.

icon: logo.png

keywords:
  - dashboard
  - mobile-crash
  - mobile network
  - mobile agent
  - HTTP data
  - android
  - ios
  - apps