id: mobile-network-performance-install

displayName: Mobile Network Performance

description: |
  This guide details how to use and instrument mobile application and install dashboard to monitor your application on mobile devices with New Relic.

icon: logo.png

install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring/

keywords:
  - dashboard
  - mobile-crash
  - mobile network
  - mobile agent
  - HTTP data
  - android
  - ios
  - apps