id: snmp
displayName: Legacy SNMP
description: Monitoring SNMP is important to capture critical network performance metrics. Download the New Relic SNMP quickstart today to proactively monitor the health of your network and understand behaviors within the network.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/snmp-monitoring-integration
icon: logo.svg
