id: f1cde389-deec-451e-8fd3-3a84631d5e83


slug: redmine
description: |
  ## Comprehensive monitoring quickstart for Redmine
  You can monitor the performance of your Ruby-on-Rails Redmine app in a complex environment with our Ruby APM agent.
  ## Why monitor your Redmine app?
  When you monitor your Redmine app's performance, you'll get a complete overview of your errors and when and where your Redmine application is slowing down. Specifically, you can use this to:
  - Identify issues that are truly important and quickly resolve them.
  - Be warned of performance issues ahead of time, giving you plenty of time to avoid downtime.
  - Prioritize resolving critical performance issues, tracing them down to their root cause, so you can solve them more quickly.
  - Monitor issues related to your Redmine app's projects.

  ## What's included?
  You'll get instant full-stack observability of your Redmine app out-of-the-box:

  - Monitor your app's custom metrics.
  - Gain code-related insights about your app's health and status.
  - Monitor your Redmine database operations and transactions.
  - Be proactively alerted about critical issues related to your app's status.

summary: |
  Quickly monitor your Redmine application by tracking performance issues with a full  end-to-end view of distributed traces 

icon: logo.png
level: New Relic
authors:
  - New Relic
title: Redmine
documentation:
  - name: Redmine integration documentation
    description: |
      Monitor the performance metrics of your Redmine instances in real-time with New Relic ruby agent.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/redmine-integration/
keywords:
  - redmine
  - ruby agent
  - ruby
installPlans:
  - redmine
dashboards:
  - redmine
alertPolicies:
  - redmine
