slug: aws-elasticache
title: AWS ElastiCache
description: "## What is AWS ElastiCache?\n\nDeploy, operate, and scale an in-memory data store or cache in the cloud.\n\n### Get started!\n\nStart monitoring AWS ElastiCache by connecting Amazon Web Services (AWS) to New Relic!\n\nCheck out our AWS ElastiCache documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.\n\n### More info\n\nCheck out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elasticache-monitoring-integration/) to learn more about New Relic monitoring for AWS ElastiCache. "
summary: Monitor AWS ElastiCache by connecting AWS to New Relic
level: New Relic
authors:
  - New Relic
keywords:
  - aws
  - amazon web service
  - database
documentation:
  - name: AWS ElastiCache installation docs
    description: Monitor AWS ElastiCache by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elasticache-monitoring-integration/
icon: logo.svg
dashboards: aws-elasticache
installPlans:
  - aws-cloudwatch-metric-streams
