
# Name of the pack
name: Memcached

# Description of the pack
description: |+
  Official New Relic pack for Memcached
  Use this pack together with the New Relic Memcached On Host Integration to get insight into the performance of your Memcached instances.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://www.newrelic.com

# Authors of the pack
authors:
  - New Relic
  - Daniel Gola

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: memcached
