# Name of the quickstart (required)
name: argocd-quickstart

# Displayed in the UI (required)
title: ArgoCD Quickstart

# Long-form description of the quickstart (required)
description: |
  ## ArgoCD Dashboard Highlights:
  - Sync Activity
  - Health Status
  - Controller Stats
  - Repo Server Stats
  - Argo Server Stats

  ## Requirements:
  1. NewRelic Kubernetes Integration (Link) with the Prometheus OpenMetrics Integration (Link)
  2. Patch the ArgoCD pods with `prometheus.io/scrape=true` podAnnotations.  This will enable the New Relic Prometheus Integration to scrape ArgoCD metrics:

      `kubectl patch deployment argocd-server -n argocd -p '{"spec": {"template":{"metadata":{"annotations":{"prometheus.io/scrape":"true","prometheus.io/port": "8083","prometheus.io/path": "metrics"}}}} }'`

      `kubectl patch statefulset argocd-application-controller -n argocd -p '{"spec": {"template":{"metadata":{"annotations":{"prometheus.io/scrape":"true","prometheus.io/port": "8082","prometheus.io/path": "metrics"}}}} }'`

      `kubectl patch deployment argocd-repo-server -n argocd -p '{"spec": {"template":{"metadata":{"annotations":{"prometheus.io/scrape":"true","prometheus.io/port": "8084","prometheus.io/path": "metrics"}}}} }'`

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Displays the performance and availability of the ArgoCD platform within Kubernetes.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - argocd
  - helm
  - kubernetes
  - k8s
  - cd
  - continuous deployment
  - argo

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - kubernetes-install

documentation:
  - name: Installation Docs
    url: docs.newrelic.com
    description: Description about this doc reference

# Content / Design
logo: logo.png
