id: vercel
displayName: Vercel
description: |
  ## About Vercel

  Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration.

  We enable teams to iterate quickly and develop, preview, and ship delightful user experiences. Vercel has zero-configuration support for 35+ frontend frameworks and integrates with your headless content, commerce, or database of choice.

icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 
      requiresAccount: true
  fallback:
    link:
      url: https://vercel.com/integrations/newrelic
keywords:
  - vercel
  - logs
  - newrelic partner
  - devops
  - cicd
  - build
  - deploy
categoryTerms:
  - newrelic partner
  - logs
