id: vercel
displayName: Vercel
description: |
  The Vercel quickstart will help monitor your end-to-end platform for developers.
icon: logo.svg
install:
  primary:
    link:
      url: https://vercel.com/integrations/newrelic
  fallback:
    link:
      url: https://docs.newrelic.com/docs/logs/forward-logs/cloudflare-logpush-forwarding
keywords:
  - vercel
  - logs
  - newrelic partner
  - devops
  - cicd
  - build
  - deploy
categoryTerms:
  - newrelic partner
  - logs
