slug: aws-apigateway-stages
title: Aws apigateway stages
description: |-
  ## What is AWS API Gateway (api)?

  Fully managed service for creating, publishing, maintaining, monitoring, and
  securing APIs at any scale. Queries made by stage. For queries by api, check
  out AWS API Gateway (APIs)

  ### Get started!

  Start monitoring AWS API Gateway by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS API Gateway documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-api-gateway-monitoring-integration) to learn more about New Relic monitoring for AWS API Gateway.
summary: Monitor AWS API Gateway (stages) by connecting AWS to New Relic
level: New Relic
authors: 
 - New Relic
keywords:
  - aws
  - amazon web service
  - api
  - stages
  - networking
documentation:
  name: AWS API Gateway installation docs
  url: >-
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-api-gateway-monitoring-integration
  description: | 
    Monitor AWS API Gateway (stages) by connecting AWS to New Relic
icon: logo.svg
dashboards: 
  - aws-apigateway-stages
installPlans: 
  - aws-cloudwatch-metric-streams
