# Sets the URL name of the quickstart on public I/O (required)
slug: snyk

# Displayed in the UI (required)
title: Snyk

# Long-form description of the quickstart (required)
description: |
  The Snyk quickstart allows you to send application security vulnerabilities of your services into New Relic.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Application security vulnerabilities from within New Relic with this integration with Snyk.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Harry Kimpel

# Keywords for filtering / searching criteria in the UI
keywords:
  - Snyk
  - Application Security
  - AppSec
  - DevSecOps
  - Vulnerabilities

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
#alerts:
#  - condition-a
#  - condition-b
dashboards:
  - snyk

installPlans:
  - third-party-snyk

# Documentation references
documentation:
  - name: Installation docs
    url: https://github.com/snyk-playground/cx-tools/tree/main/webhook-examples#13-new-relic-events
    description: Installation and configuration instructions for Snyk and the Snyk quickstart.

# Content / Design
icon: logo.svg
website: https://www.snyk.io
