id: 658d36f3-aa96-4e74-93da-b74eefcaabd3
# Sets the URL name of the quickstart on public I/O (required)
slug: snyk

# Displayed in the UI (required)
title: Snyk

# Long-form description of the quickstart (required)
description: |
  The Snyk quickstart allows you to send application security vulnerabilities of your services into New Relic. We leverage webhooks on the Snyk platform to trigger an Azure Function App that acts as a proxy between Snyk and New Relic.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Application security vulnerabilities from within New Relic with this integration by Snyk.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Harry Kimpel

# Keywords for filtering / searching criteria in the UI
keywords:
  - vulnerabilities
  - newrelic partner
  - azure
  - apm
  - security
  - snyk

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
#alerts:
#  - condition-a
#  - condition-b
dashboards:
  - snyk

installPlans:
  - third-party-snyk

# Documentation references
documentation:
  - name: Installation docs
    url: https://github.com/snyk-playground/cx-tools/tree/main/Snyk-to-New-Relic-Security-API
    description: Installation and configuration instructions for Snyk and the Snyk quickstart.

# Content / Design
icon: logo.svg
website: https://www.snyk.io
