id: 475dec69-10c9-4bc6-8312-3caa266fb028

# Name of the pack
name: php

# Title of the pack
title: PHP

summary: Monitor PHP with New Relic's PHP agent

# Description of the pack
description: |-
  ## What is PHP?

  PHP is a general-purpose scripting language especially suited to web development.

  ## Get started!

  Leverage community expertise and instantly get value out of your telemetry data. This quickstart automatically instruments PHP with the New Relic PHP agent, and allows you to further leverage New Relic's APM capabilities by setting up [custom dashboards](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/), [errors inbox](https://docs.newrelic.com/docs/apm/apm-ui-pages/errors-inbox/errors-inbox/), [transaction tracing](https://docs.newrelic.com/docs/apm/transactions/transaction-traces/introduction-transaction-traces/), and [service maps](https://docs.newrelic.com/docs/understand-dependencies/understand-system-dependencies/service-maps/introduction-service-maps/).

  ## More info

  Check out the [documentation](https://docs.newrelic.com/docs/agents/php-agent/) to learn more about New Relic monitoring for PHP. 

# Support level: New Relic | Verified | Community
level: New Relic

# Design
logo: logo.jpg
website: https://www.php.net/

# Authors of the pack
authors:
  - New Relic
  - Stijn Polfliet

documentation:
  - name: PHP
    description: |
      PHP is a general-purpose scripting language especially suited to web development.
    url: https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements/

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-apm
    name: php
keywords:
  - apm
  - php
  - language agent

installPlans:
  - php-agent
