id: 475dec69-10c9-4bc6-8312-3caa266fb028
# Name of the pack
name: PHP

# Description of the pack
description: |+
  # Complete Solution to PHP Monitoring
  Use a PHP server monitor agent and let developers see the bigger picture with a high-level summary of their app in a comprehensive PHP dashboard. Help teams monitor the app's Apdex, build architectural maps, and find and resolve errors quickly.

  ## Monitoring PHP Performance
  A PHP server monitor does more than monitor app and server functions. It collects and analyzes business data that drive data-driven decisions. For example, you can organize, query data using NRQL, and visualize data (in customizable interactive dashboards) that directly impact customer experiences. 

  New Relic's instant observability kit lets you connect up to 500 agents or apps to one daemon. You can also use the daemon as a proxy between the New Relic platform and the agent.

  ## How to Speed Up PHP with New Relic
  Identify slow AJAX request performance issues at a glance through New Relic's PHP dashboard that boasts broader visibility. It can provide a good indication of where you should concentrate your efforts. Then, you can inspect the element and address potential errors quickly.

  Dive into the performance details with New Relic's kit to examine code-level transaction traces, query traces, and error traces. With this approach, you can provide extensive insights into potential PHP issues.

  PHP performance monitoring with New Relic plugins offers advanced features, including:
  - Browser monitoring
  - Custom instrumentation
  - Distributed tracing
  - Multiple accounts
  - Recording deployments

  ## What’s Included?
  New Relic + PHP Quickstart - New Relic’s performance monitoring tool provides instant observability out-of-the-box. This pack includes:
  - Alerts including error rates, duration, and throughput
  - Multiple ready-to-use dashboards including throughput, error rate %, transaction time in ms, and latest transactions

  ## Value of .PHP Quickstarts
  New Relic's instant observability quickstart helps developers leverage broader visibility in a PHP dashboard to resolve errors and speed up processes that enhance customer experiences. As New Relic is SaaS-based, you won't have to spend your time onboarding or maintaining it. 

# Support level: New Relic | Verified | Community
level: New Relic

# Design
logo: logo.jpg
website: https://www.php.net/

# Authors of the pack
authors:
  - New Relic
  - Stijn Polfliet

documentation:
  - name: PHP
    description: >-
      PHP is a general-purpose scripting language especially suited to web development.
    url: https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements/

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-apm
    name: php
keywords:
  - apm
  - php
  - language agent

installPlans:
  - php-agent
