
slug: aerospike
description: |
  ## Comprehensive monitoring quickstart for Aerospike
  New Relic detects your Aerospike metrics like uptime, Info Stats, Memory, Client connections, etc. Monitor the performance metrics of your Aerospike instances in real-time with New Relic APM.

  ## Why monitor Aerospike?
   Using Aerospike Database instrumentation, you can monitor cluster health, database performance, and alerts based on instantaneous and cumulative metrics.

  ## What’s included in this quickstart?
  New Relic's Aerospike monitoring quickstart boasts instant full-stack observability out-of-the-box:
  - High value alerts for your Aerospike (Failed generation, Unavailable partitions, Uptime and Heap efficiency pct).
  - Dashboards (uptime, info stats, memory, client connections, etc)
summary: |
  Instrument and monitor your Aerospike with the New Relic's Infrastructure agent. Analyze your performance data using our pre-built dashboards and alert conditions.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana reddy
title: Aerospike
documentation:
  - name: Aerospike integration documentation
    description: |
      Monitor the performance metrics of your Aerospike instances in real-time with New Relic APM.
    url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/aerospike-integration/
installPlans:
  - aerospike
dataSourceIds:
  - aerospike
keywords:
  - aerospike
  - real-time data platform
dashboards:
  - aerospike
alertPolicies:
  - aerospike
