slug: aws-connect
title: AWS Connect
description: "## What is AWS Connect?\n\nBuild cloud-based omnichannel support centers to serve customers dynamically.\n\n### Get started!\n\nStart monitoring AWS Connect by connecting Amazon Web Services (AWS) to New Relic!\n\nCheck out our AWS Connect documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.\n\n### More info\n\nCheck out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-connect-monitoring-integration/) to learn more about New Relic monitoring for AWS Connect. "
summary: Monitor AWS Connect by connecting AWS to New Relic
level: New Relic
authors:
  - New Relic
keywords:
  - aws
  - amazon web service
documentation:
  - name: AWS Connect installation docs
    description: |
      Monitor AWS Connect by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-connect-monitoring-integration/
icon: logo.svg
dashboards: aws-connect
installPlans:
  - aws-cloudwatch-metric-streams