slug: aws-dynamodb
title: AWS DynamoDB
description: |-
  ## What is AWS DynamoDB?

  Fully managed NoSQL cloud database that supports both document and key-value
  store models.


  ### Get started!

  Start monitoring AWS DynamoDB by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS DynamoDB documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.summary: Monitor Aws dynamodb by connecting AWS to New Relic
summary: Monitor DynamoDB by connecting AWS to New Relic
level: New Relic
authors: New Relic
keywords:
  - aws
  - amazon web services
  - database
documentation:
  - name: AWS DynamoDB installation docs
    description: |
      Monitor AWS DynamoDB by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-dynamodb-monitoring-integration/
icon: logo.svg
dashboards: 
  - aws-dynamodb
installPlans:
  - aws-cloudwatch-metric-streams
alertPolicies:
  - aws-dynamodb