id: network-ktranslate-health
displayName: Network KTranslate Container Health
description: |
  Easily install a curated dashboard to monitor the health of your ktranslate containers for New Relic Network Performance Monitoring.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: f7119d5e-32b7-45ff-a814-0dca91ae0493
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/network-performance-monitoring/advanced/ktranslate-container-health
keywords:
  - npm
  - network
  - networking
  - ktranslate
  - kentik
  - infrastructure
  - newrelic partner
categoryTerms:
  - newrelic partner
