
slug: ado-dotnet
description: |
  ## Comprehensive monitoring quickstart for Ado.net

  With New Relic's ADO.NET monitoring system, you can observe your ADO.NET data set in real-time. Our .NET agent will also let you correlate transactions moving across your application environment and troubleshoot while working in a live development environment.


  ## Why monitor ADO.NET?

  Discovering data access API calls can help in identifying the following issues:
    - Inaccessible databases or issues with the network library.
    - Database and client software schema incompatibility.
    - Problems occur when different ADO.NET components interact with one another or your own components.
    - Whether hard-coded or created by an application, incorrect SQL.
    - Flawed programming logic.

  ## What’s included in this quickstart?

  The ADO.NET monitoring quickstart from New Relic provides immediate full-stack observability:
    - Alerts (High load connection, Hard connects exceeding max limit, Pool size exceeding optimum limit).
    - Dashboards (Hard connects per second, Hard disconnects per second, Number of active connections, Soft connects per second,  and more).
    - Alerts inform end users about the quality of their applications on a proactive basis.
    - Monitor web transactions.


summary: |
  Discover more about ADO.NET, the importance of New Relic's ADO.NET quickstart, the advantages of ADO.NET monitoring, and the best features to look for in this quickstart.
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: ADO.NET
documentation:
  - name: ADO.NET installation docs
    description: |
      Open-source web application framework developed by Microsoft, which
      implements the model-view-controller pattern.
    url: >-
      https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-core
keywords:
  - apm
  - dotnet
  - .net
  - ado.net
  - ado-dotnet
installPlans:
  - dotnet-agent

dashboards:
  - ado-dotnet
alertPolicies:
  - ado-dotnet
