id: flutter-android
displayName: Flutter Android
description: |
  Instrument and monitor your Flutter Android application with the New Relic’s Android and Flutter agents. Analyze your performance data (Errors, App crashes, App launches, HTTPs response and Network failures) in view of the best code diagnosis, improvement, and optimization.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application/

keywords:
  - flutter
  - flutter android application
  - android agent
  - flutter agent