id: flutter-android
displayName: Flutter Android
description: |
  Instrument and monitor your Flutter Android app with New Relic’s Android and Flutter agent. Analyze your performance data (Errors, Application Crashes, App Launches and App Installations) to diagnose, improve, and optimize your code.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application/

keywords:
  - flutter
  - flutter android application
  - android agent
  - flutter agent