id: amazon-verified-access
displayName: Amazon Verified Access
description: Monitor Amazon Verified Access by sending Access logs to New Relic
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-verified-access-monitoring-integration/
icon: logo.svg
