id: 2dff13b6-0fac-43a6-abc6-57f0a3299639
name: dotnet
description: |-
  ## What is .NET?

  Learn more about.NET Framework, the importance of monitoring .NET, the ideal features of a .NET monitor, and the unique value of New Relic's .NET Instant Observability pack. 


  ## Get started!

  Leverage community expertise and instantly get value out of your telemetry data. This quickstart automatically instruments .NET with the New Relic .Net agent, and allows you to instantly monitor your .Net application with out-of-the-box dashboards and alerts. Further leverage New Relic's APM capabilities by setting up [errors inbox](https://docs.newrelic.com/docs/apm/apm-ui-pages/errors-inbox/errors-inbox/), [transaction tracing](https://docs.newrelic.com/docs/apm/transactions/transaction-traces/introduction-transaction-traces/), and [service maps](https://docs.newrelic.com/docs/understand-dependencies/understand-system-dependencies/service-maps/introduction-service-maps/).

  ## More info

  Check out the [documentation](https://docs.newrelic.com/docs/agents/net-agent/getting-started/introduction-new-relic-net/) to learn more about New Relic monitoring for .NET. 
summary: |-
  Monitor .NET with New Relic's .NET agent
icon: icon.svg
logo: logo.svg
level: Community
authors:
  - New Relic
  - Emil Hammarstrand
title: .NET
documentation:
  - name: .NET installation docs
    description: |
      A developer platform with tools and libraries for building web, mobile,
      desktop, games, IoT, cloud, and microservices.
    url: >-
      https://docs.newrelic.com/docs/agents/net-agent/getting-started/compatibility-requirements-net-framework-agent
keywords:
  - apm
  - dotnet
  - language agent

installPlans:
  - dotnet-agent
.NET Framework, the importance of monitoring .NET, the ideal features of a .NET monitor, and the unique value of New Relic's .NET Instant Observability pack. 
icon: icon.svg
logo: logo.svg
level: Community
authors:
  - New Relic
  - Emil Hammarstrand
title: .NET
documentation:
  - name: .NET installation docs
    description: |
      A developer platform with tools and libraries for building web, mobile,
      desktop, games, IoT, cloud, and microservices.
    url: >-
      https://docs.newrelic.com/docs/agents/net-agent/getting-started/compatibility-requirements-net-framework-agent
keywords:
  - apm
  - dotnet
  - language agent

installPlans:
  - dotnet-agent
