id: cb995039-39d8-44d9-97c3-58174a1337f2
# Name of the quickstart (required)
# sets the URL name of the quickstart on public I/O
slug: datastream2

# Displayed in the UI (required)
title: Akamai Datastream2

# Long-form description of the quickstart (required)
description: |
  DataStream2 captures performance and security logs from your delivery properties and streams them in near real-time to provide complete monitoring.

  For more information please go to https://techdocs.akamai.com/datastream2/docs

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  The Datastream2 quickstart will enable you to monitor and analyze your performance and security logs.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Gayatri S (Akamai Technologies)

# Keywords for filtering / searching criteria in the UI
keywords:
  - akamai
  - logs
  - cdn
  - datastream
  - performance
  - security

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - third-party-datastream2-akamai

# Documentation references
documentation:
  - name: Installation docs
    url: https://techdocs.akamai.com/datastream2/docs/stream-logs/
    description: Configure Akamai Datastream2 streaming logs to New Relic

# Content / Design
icon: logo.png
website: https://www.akamai.com/