id: d8653351-59f6-431a-8839-012dd6f5b16d
# Name of the quickstart (required)
name: oma-data-gov

# Displayed in the UI (required)
title: Data Ingest Governance Quickstart

# Long-form description of the quickstart (required)
description: |
Data ingest governance is a practice of ensuring optimal value for telemetry data collected by an organization particulary a complex organization with numerous business units and working groups.  The objective is get appropriate ROI for investimate in telemetry data.
summary: |
Generate a baseline analysis of your telemtry ingest and use those insights to optimize and forecast future ingest.
# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Jim Hagan (New Relic)
  - Kim Hickey (New Relic)

# Keywords for filtering / searching criteria in the UI
keywords:
  - oma
  - observabilty maturity
  - data ingest governance
  - optimize data ingest

documentation:
  - name: Installation Docs
    url: >- https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/introduction/
      
    description:  | 
      Generate a baseline analysis of your telemtry ingest and use those insights to optimize and forecast future ingest.
# Content / Design
logo: logo.png
website: https://www.newrelic.com
