slug: flutter-ios
description: |
  ## Comprehensive monitoring quickstart for Flutter iOS
  
  Monitor your Flutter iOS applications and analyze performance bottlenecks while operating in a live development environment. You can use this dashboard to visualize your web user experience with your application rendition.
  
  ## Why monitor Flutter iOS?
  Monitoring app performance helps you to take a preventative approach to enhance quality rather than waiting for a crash, issue, or user complaint to occur. The Newrelic’s iOS and  Flutter Agent allows you to track important metrics including network failures and http response, slow launches, tracking custom traces, and more.

  By prioritizing active issues and marking errors as corrected, you may optimize the process once you have a comprehensive picture of all releases. Identify which release the problem first appeared in, merge duplicates, and assess whether it may get worse in the future. Add commit information to send deploy emails instantly and suggest an owner for each application error.


  ## What’s included in this quickstart?
  New Relic's iOS and flutter agents captured the metrics out of the box:

  - Be alerted on critical issues affecting your Flutter application.
  - Dashboards (error rate, app launches, app installations, app crashes and more).
  - Monitor Flutter Dart exceptions and Errors.
  - Monitor HTTP response, HTTP errors and Mobile events.
  
  Install and start monitoring your data today! 
  
summary: |
  Instrument and monitor your Flutter iOS application with New Relic’s iOS and Flutter Agent. Analyze your performance data (Errors, Application Crashes, App Launches and App Installations) to diagnose, improve, and optimize your code.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Flutter iOS
documentation:
  - name: Flutter iOS integration documentation
    description: |
      Monitor the performance metrics of your Flutter iOS application instances in real-time with New Relic's iOS and Flutter agent.
    url: >-
      https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application/
keywords:
  - flutter
  - flutter ios application
  - ios agent
  - flutter agent
dashboards:
  - flutter-ios
alertPolicies:
  - flutter-ios
dataSourceIds:
  - flutter-ios
