slug: flutter-ios
description: |
  ## Comprehensive monitoring quickstart for Flutter iOS
  
  Monitor your Flutter applications and analyze performance bottlenecks while operating in a live development environment. You can use this dashboard to visualize your web user experience with your application rendition.
  
  ## Why monitor Flutter iOS?
  Monitoring app performance enables you to take a preventative approach to improve quality, rather than waiting for issues, crashes, or user complaints. With New Relic's iOS and Flutter agent, you can track network failures, slow launches, custom traces, and more.

  By prioritizing active issues and marking errors as corrected, you may optimize the process once you have a comprehensive picture of all releases. Identify which release the problem first appeared in, merge duplicates, and assess whether it may get worse in the future. Add commit information to send deploy emails instantly and suggest an owner for each application error.



  ## What’s included in this quickstart?
  New Relic's iOS and flutter agents captured the metrics out of the box:

  - Be alerted on critical issues affecting your Flutter application
  - Dashboards (error rate, app launches, app installations, app crashes and more)
  - Monitor Flutter Dart exceptions and Errors
  - Monitor HTTP response, HTTP errors and mobile events
  
summary: |
  Identify and optimize Flutter iOS app performance with New Relic Flutter iOS Monitoring.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Flutter iOS
documentation:
  - name: Flutter iOS integration documentation
    description: |
      Monitor the performance metrics of your Flutter iOS application instances in real-time with New Relic's iOS and Flutter agent.
    url: >-
      https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application/
keywords:
  - flutter
  - flutter ios application
  - ios agent
  - flutter agent
dashboards:
  - flutter-ios
alertPolicies:
  - flutter-ios
dataSourceIds:
  - flutter-ios
