slug: aws-athena
title: AWS athena
description: |-
  ## What is Amazon Athena?

  Serverless, interactive query service to query data and analyze big data in
  Amazon S3 using standard SQL.


  ### Get started!

  Start monitoring Amazon Athena by connecting Amazon Web Services (AWS) to New Relic!

  Check out our Amazon Athena documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  New Relic offers an integration for reporting your Amazon Athena data. [This documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-athena-monitoring-integration)  explains how to activate this integration and describes the data that can be reported.
summary: |-
  Monitor AWS Athena by connecting AWS to New Relic
level: New Relic
authors: 
  - New Relic
keywords:
  - aws
  - amazon web service
  - database
documentation:
  name: AWS Athena installation docs
  url: >-
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-athena-monitoring-integration
  description: ''
icon: logo.svg
dashboards: aws-athena
installPlans: 
  - aws-cloudwatch-metric-streams
