# Name of the quickstart (required)
name: slack-for-codestream

# Displayed in the UI (required)
title: Slack for CodeStream

# Long-form description of the quickstart (required)
description: |
  Slack is a messaging app for business that connects people to the information that they need. 

  When you post a comment, issue, or feedback request, your teammates are notified via the activity feed, and potentially via email. Sometimes, though, you might want to share to Slack as well. This allows you to reach people who haven’t yet joined CodeStream or maybe don’t spend a lot of time in their IDE.

  (Check out our documentation)[https://docs.newrelic.com/docs/codestream/codestream-integrations/slack-integration] to connect New Relic CodeStream to your team's Slack channel.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Connect New Relic CodeStream to your team's Slack channel.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - slack
  - codestream
  - ide
  - errors inbox

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config

documentation:
  - name: Slack Integration Docs
    url: https://docs.newrelic.com/docs/codestream/codestream-integrations/slack-integration
    description: Documentation about the New Relic - Slack CodeStream integration

# Content / Design
logo: logo.png
website: https://www.newrelic.com
