id: browser-docs
displayName: Browser monitoring
description: |
  With New Relic One's browser monitoring solution, you get full visibility into the complete webpage life cycle of your application or website. Browser measures page load timing, also known as Real User Monitoring (RUM).
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/
