id: fdd86b8b-7cc8-4528-a8e7-4cab7072304d
slug: dojo

description: |
  ## Comprehensive monitoring quickstart for Dojo
  With the help of New Relic's Dojo dashboard, you can track your application's core web vitals, how much time your users spend on your site, and critical browser performance metrics like initial page load and pages with Javascript errors.

  ## Why monitor your Dojo app?
  - As you know, you Dojo web app is a complex interaction of widgets, data flows, and data stores. By monitoring your Dojo app with New Relic, you can start to gain insight into its performance and areas where it can be improved. 
  - By understanding your app's performance, you can prioritize resolving critical performance issues by tracing the problem to its source.
  - Help you identify issues that are truly important and quickly resolve them. Gain knowledge of performance issues in advance and thus giving you ample time to avoid application downtime.
  - Performance provides you with the information you need to not only prioritize critical performance issues, but also trace them down to the root cause and solve them more quickly.
  - View the overall health of your production environment in order to quickly identify and resolve problems with crippled services.


  ## What’s included in this quickstart?
  New Relic's Dojo monitoring quickstart boasts instant full-stack observability out-of-the-box:

  With this quickstart, you can:
  - Use interactive, continually updating dashboards to see your app's performance, such as load time distribution and AJAX response times.
  - With alerts, be notified about critical issues involving your app's performance.

summary: |
  Monitor your Dojo application by tracking performance issues with a full end-to-end view of distributed traces.

icon: logo.png
level: New Relic
authors:
  - New Relic
title: Dojo
documentation:
  - name: Dojo integration documentation
    description: |
      Monitor the performance metrics of your Dojo instances in real-time with New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/dojo-io-integration/
keywords:
  - dojo
  - browser monitoring
installPlans:
  - dojo
dashboards:
  - dojo
alertPolicies:
  - dojo
