id: mern-stack
displayName: MERN Stack Integration
description: |
  ## Comprehensive MERN stack monitoring system:
  MERN is a free and open-source JavaScript software stack for building dynamic web sites and web applications. Each of these 4 powerful technologies provides an end-to-end framework for the developers to work in and each of these technologies play a big part in the development of web applications.

  ## What should you look for in a MERN dashboard?
  Metrics of MongoDB, i.e. number of active connections, database details, usage time and many more.
  Metrics of ExpressJS, NodeJS, i.e. number of web transactions, top transactions and the error transactions, memory usage and many more.
  Metrics of ReactJS, i.e. number of viewed urls, page views by city, ajax requests and many more. You are also free to create your own chart by using the stored metrics.

  ## What’s included in the MERN quickstart?
  Install this quickstart to install preconfigured observability solutions:
  - Multiple high-value alerts, including page views by city and ajax requests
  - Informative dashboards (Top transactions, Error transactions, and more)

install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/browser/browser-integrations/mexn-integration/

icon: logo.png

keywords:
  - MERN
  - MongoDB
  - ExpressJS
  - ReactJS
  - NodeJS
  - Fullstack
