name: elasticsearch
title: Elasticsearch query Java Agent Extension
description: |
  # What is elasticsearch?
Elasticsearch is a search engine based on the Lucene library. It provides a distributed, multitenant-capable full-text search engine with an HTTP web interface and schema-free JSON documents.
Elasticsearch provides a full Query DSL (Domain Specific Language) based on JSON to define queries

summary: |
  Java agent extension to monitor elasticsearch queries as dataStore queries with New Relic. Once deployed, elasticsearch queries begin to show up in the New Relic UI under Databases for the application using elasticsearch queries.

icon: icon.svg
logo: logo.svg
level: Community
website: https://www.elastic.co/

keywords:
  - nrlabs
  - nrlabs-data
  - apm
  - java
  - elasticsearch

authors:
  - New Relic Labs

documentation:
  - name: Java agent extension for Elasticsearch queries
    description: |
      Java Agent instrumentation extension to track and record ElasticSearch queries as dataStore queries
    url: >-
      https://github.com/newrelic-experimental/newrelic-java-elasticsearch
