name: AWS Cloudwatch plugin for Logs
description: Collect and manage log data coming in from Amazon's Cloudwatch observability framework.
icon: icon.svg
logo: logo.svg
level: Community
authors:
  - New Relic
documentation:
  - name: AWS Cloudwatch plugin for Logs
    description: Collect and manage log data coming in from Amazon's Cloudwatch observability framework.
    url: >-
      https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/aws-lambda-sending-cloudwatch-logs/
