id: b70291ad-ff88-4ff9-9173-d4b2f99656af

# Name of the quickstart (required)
name: puppet

# Displayed in the UI (required)
title: Puppet

# Long-form description of the quickstart (required)
description: |
  Puppet is a configuration management tool used to manage various stages of the
  IT infrastructure lifecycle.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Puppet is a configuration management tool used to manage various stages of the
  IT infrastructure lifecycle.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - automation
  - devops
  - sre
  - gitops

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
documentation:
  - name: Puppet installation docs
    description: |
      Puppet is a configuration management tool used to manage various stages of
      the IT infrastructure lifecycle.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/config-management-tools/configure-new-relic-infrastructure-puppet
  - name: Puppet Forge
    description: Puppet Forge page for the New Relic Puppet Module
    url: >-
      https://forge.puppet.com/modules/newrelic/newrelic_infra

# Content / Design
logo: logo.svg
website: https://forge.puppet.com/modules/newrelic/newrelic_infra
