# Name of the quickstart (required)
# sets the URL name of the quickstart on public I/O
name: hcp-envoy

# Displayed in the UI (required)
title: HCP Envoy

# Long-form description of the quickstart (required)
description: |-
  This Quickstart provides example configuration for HCP Envoy reporting metrics into New Relic via New Relic's statsd integration.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |-
  HCP Envoy Quick Start sample statsd configuration

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - New Relic Labs

# Keywords for filtering / searching criteria in the UI
keywords:
  - hcp
  - hcp-envoy
  - hashicorp
  - envoy
  - envoy-proxy
  - nrlabs
  - nrlabs-data

# Documentation references
documentation:
  - name: Configuration documentation
    url: https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/hashicorp/hcp-envoy/configuration.md
    description: HCP Envoy configuration documentation

# Content / Design
icon: logo.svg
