id: netlify-logs

displayName: Netlify Logs

description: |
  Netlify is an all-in-one platform for automating modern web projects. Replace your hosting infrastructure, continuous integration, and deployment pipeline with a single workflow. Use this quickstart to quickly parse traffic and function logs from Netlify into meaningful metrics in New Relic.

logo: logo.png

install:
  primary:
    nerdlet: nr1-install-newrelic.quickstart-installation-plan
    nerdletState:
      quickstart_id: 63f08781-18ad-4a89-ae63-49718deee041
  requiresAccount: true
  secondary:
    link: https://docs.netlify.com/monitor-sites/log-drains/

keywords:
  - netlify
  - logs
  - traffic logs
  - function logs
  - log drains
  - jamstack
  - serverless functions
  - newrelic partner

categoryTerms:
  - newrelic partner
  - logs