id: netlify-logs
displayName: Netlify Logs
description: |
  Netlify is an all-in-one platform for automating modern web projects. Replace
  your hosting infrastructure, continuous integration, and deployment pipeline
  with a single workflow. Use this quickstart to quickly parse traffic and
  function logs from Netlify into meaningful metrics in New Relic.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 63f08781-18ad-4a89-ae63-49718deee041
      requiresAccount: true
  fallback:
    link:
      url: https://docs.netlify.com/monitor-sites/log-drains/
keywords:
  - netlify
  - logs
  - traffic logs
  - function logs
  - log drains
  - jamstack
  - serverless functions
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
  - logs
  - browser agent
