# Name of the pack name: Xamarin-bindings

# Displayed in the UI
title: Xamarin bindings to Newrelic's Mobile SDK

# Long-form description of the pack
description: |
  This repo/project provides Xamarin bindings for Newrelic's iOS and Android SDK's. The dll produced after building the bindings can be used in your Xamarin project.

# Displayed in search results and recommendations. Summarizes a packs functionality.
summary: |
  This project provides Xamarin bindings for Newrelic's iOS and Android SDK's

# Support level: New Relic | Verified | Community 
level: Community

# Authors of the pack (required)
authors:
  - New Relic Labs

# Keywords for filtering / searching criteria in the UI
keywords:
  - nrlabs
  - nrlabs-data
  - xamarin
  - hybrid mobile
  - C-sharp mobile

documentation:
  - name: README.md has instructions on how to build the Xamarin bindings. API documentation is under iOS and Android docs
    url: docs.newrelic.com
    description: The bindings are C-sharp wrapper API's over iOS and Android API's. Please refer to Newrelic's iOS and Android SDK's documentation on API usage and descriptions https://docs.newrelic.com/docs/mobile-monitoring/
    url: >-
      https://github.com/newrelic-experimental/newrelic-xamarin-binding

# Content / Design
icon: icon.jpeg
logo: logo.png
website: https://dotnet.microsoft.com/apps/xamarin
