
# Name of the pack
name: Nagios

# Description of the pack
description: |+
  Official New Relic pack for Nagios
  Use this pack together with the New Relic Nagios On Host Integration to run Nagios custom scripts and display the data in New Relic.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.jpeg
website: https://www.nagios.org/

# Authors of the quickstart
authors:
  - New Relic
  - Jakub Kotkowiak
  - Stijn Polfliet

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: nagios
