slug: aws-autoscaling
title: AWS Autoscaling
description: |-
  ## What is AWS Auto Scaling?

  Launch or terminate EC2 instances automatically, adapting capacity based on
  user-defined policies, schedules, and health checks.


  ### Get started!

  Start monitoring AWS Auto Scaling by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS Auto Scaling documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-auto-scaling-monitoring-integration) to learn more about New Relic monitoring for AWS Auto Scaling.
summary: |-
  Monitor AWS Auto Scaling by connecting AWS to New Relic
level: New Relic
authors: New Relic
keywords:
  - aws
  - amazon web service
documentation:
  name: WS Auto Scaling installation docs
  url: >-
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-auto-scaling-monitoring-integration
  description: |
      Monitor AWS Auto Scaling by connecting AWS to New Relic.
icon: logo.svg
dashboards: 
 - aws-autoscaling
installPlans: 
  - aws-cloudwatch-metric-streams
