id: 9b39d6c5-8623-4fa6-9fef-96305b5ab875
# Name of the quickstart (required)
slug: traefik

# Displayed in the UI (required)
title: Traefik (Prometheus)

# Long-form description of the quickstart (required)
description: |
  This quickstart was built and tested based on Traefik metrics sent to New Relic using Prometheus Agent or Prometheus server.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Easily install a curated dashboard to monitor the health of your Traefik instances.

# Support level: New Relic | Verified | Community (required)
level: Verified

# Authors of the quickstart (required)
authors:
  - New Relic
  - Zack Mutchler
  - Mir Ansar

# Keywords for filtering / searching criteria in the UI
keywords:
  - traefik
  - prometheus
  - remote_write
  - promql
  - grafana

documentation:
  - name: Prometheus installation docs
    description: |
      Use Prometheus remote_write or Prometheus Agent
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic
  - name: Traefik Documentations
    description: |
      Traefik Integration Documentation
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/traefik-integration

installPlans:
  - setup-prometheus
  - setup-prometheus-agent-mode

# Content / Design
icon: logo.svg

dashboards:
  - traefik

alertPolicies:
  - traefik