slug: dapr
title: Dapr
description: |
  The Dapr quickstart allows you to add meaningful dashboards to New Relic that highlight key aspects of the Dapr platform.

  A guide on how to set-up New Relic for distributed tracing with Dapr can be found [here](https://docs.dapr.io/operations/monitoring/tracing/newrelic/).
summary: |
  Dapr is a portable, event-driven runtime that makes it easy for any developer to build resilient, stateless and stateful applications that run on the cloud and edge and embraces the diversity of languages and developer frameworks.
level: Community
authors:
  - Harry Kimpel
keywords:
  - apm
  - dapr
dashboards:
  - dapr
installPlans:
  - third-party-dapr
dataSourceIds:
  - dapr-metrics
  - dapr-system-services
documentation:
  - name: Installation docs
    url: https://docs.dapr.io/operations/monitoring/tracing/newrelic/
    description: How-To Set-up New Relic for distributed tracing.
icon: logo.svg
website: https://www.dapr.io
