id: synthetics-page-load-performance
displayName: Synthetics Page Load performance
description: Full page load of a given URL which provides deep data insights like resource breakdowns and timelines.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
icon: logo.svg
