id: ad9f635b-6496-48a8-b373-9fab81a7f719
# Name of the pack
name: mysql

# Description of the pack
description: |+
  # MySQL Performance Monitoring

  Applications powered by relational database management systems demand the user to understand how the application uses it. Quickly identify and resolve the source server issues with MySQL performance monitoring tools. 

  Identify query optimization metrics and more within a single MySQL dashboard (negating the need to juggle multiple dashboards) and ensure the highest application performance with this approach. 

  ## MySQL Monitoring
  Sift through the source code and make improvements or create a fork and build your own as integrations are open source. It’s easier to use a performance monitoring tool that helps optimize infrastructure monitoring protocols by collecting inventory and metrics from your database. You can then analyze the data to ascertain server health and identify the source of potential problems.

  ## New Relic + MySQL - Your Ideal Tool for Better Monitoring
  New Relic’s instant observability quickstart helps development teams identify and focus on both high load and/or slow response times. Unlike other performance monitoring tools, New Relic is a powerful proactive remote monitoring solution that provides a comprehensive view from a single MySQL dashboard. 

  Whenever you pair it with New Relic, there are almost no boundaries to what you can monitor. You also have the option of liberally intertwining the technology and New Relic. 


  ## What’s Included?
  New Relic MySQL performance monitoring is available with instant observability out-of-the-box. The MySQL quickstart has both dashboards and alerts, including:

  - Alerts (pending reads and writes, max connection errors/second, questions/second, and slow queries/second)
  - Dashboards (operations/second, slow queries per minute by node, active connections by node, and more)

  ## Value of MySQL Quickstart
  New Relic’s instant observability quickstart helps developers accelerate time to value. You can use this approach to help reduce administrative overheads. As New Relic is SaaS-based, you also don’t have to worry about maintenance or onboarding. You can implement this robust performance and infrastructure monitoring tool within minutes.
summary: |+
  Engage in MySQL performance monitoring with New Relic and benefit from improved performance, query optimization, and lower administrative overheads with our instant observability quickstart.

# Support level
level: New Relic

# Design
logo: logo.png
website: https://en.wikipedia.org/wiki/MySQL

# Authors of the pack
authors:
  - New Relic

documentation:
  - name: MySQL
    description: >-
      Open source relational database with more than 20 years of community development and support.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration/

installPlans:
  - infra-agent-targeted
  - mysql-integration
keywords:
  - infrastructure
  - database

