slug: aws-chatbot
description: |-
  ## What is Amazon Chatbot?
  AWS Chatbot is an AWS service that enables DevOps and software development teams to use messaging program chat rooms to monitor and respond to operational events in their AWS Cloud. AWS Chatbot processes AWS service notifications from Amazon Simple Notification Service (Amazon SNS), and forwards them to chat rooms so teams can analyze and act on them immediately, regardless of location.
  ### Get started!
  Start monitoring Amazon Chatbot by using AWS Kenesis Firehose to send logs to New Relic! Take a look at our documentation for information on how to set this integration.
  ### More info
  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-chatbot-monitoring-integration/) to learn more about New Relic monitoring for Amazon Chatbot.
summary: |-
  Monitor Amazon Chatbot by streaming Firehose logs into New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: Amazon Chatbot
documentation:
  - name: Amazon Chatbot installation docs
    description: |
      Monitor Amazon Chatbot by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-chatbot-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - networking
dashboards:
  - aws-chatbot
installPlans:
  - aws-chatbot
dataSourceIds:
  - amazon-chatbot