id: aerospike
displayName: Aerospike
description: |
  Instrument and monitor your Aerospike with the New Relic Infrastructure agent. Analyze your performance data using our pre-built dashboards and alert conditions.
install:
  primary:
    link:
      url: https://docs.newrelic.com/
icon: logo.png

keywords:
  - aerospike
  - real-time data platform