
# Name of the pack
name: JMX (Java)

# Description of the pack
description: |+
  Official New Relic pack for JMX
  Use this pack together with the New Relic JMX On Host Integration to get insight into the performance of your Java instances.

# Support level
level: New Relic

# Design
icon: icon.svg
logo: logo.png
website: https://docs.oracle.com/javase/tutorial/jmx/overview/index.html

# Authors of the quickstart
authors:
  - New Relic
  - Jakub Kotkowiak

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: jmx
