id: databricks
displayName: Databricks Integration

description: |
  Databricks is an orchestration platform for Apache Spark. Instantly monitor Databricks Spark applications with our New Relic Spark integration quickstart. Our integration provides a script run in a notebook to generate an installation script, which you can attach to a cluster and populate Spark metrics to New relic Insights events. Easily track the health of your Databricks clusters, fine-tune your Spark jobs for peak performance, and troubleshoot problems with this quickstart.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 533cdd19-8232-42cb-b134-e7d17bfff581
      requiresAccount: true
  fallback:
    link:
      url: https://github.com/newrelic-experimental/nri-spark#databricks-init-script-creator-notebook

keywords:
  - nrlabs
  - nrlabs-data
  - apache spark
  - spark
  - databricks
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
