slug: mobile-crash-analytics-quickstart

# Used as the display name for the quickstart
title: Mobile Crash Analytics

description: |
  ## Crash Analytics Monitoring Quickstart
  
  Get deep visibility into the mobile application crash frequency, affected versions. 

  Alert and identify potential issues, or simply use for remote monitoring. 

summary: |
  Monitor and alert on mobile application crash on user devices to ensure ongoing reliability and performance. 

level: Community
icon: logo.png

authors:
  - Siddhartha Khare

keywords:
  - dashboard
  - mobile-crash
  - crash analytics
  - crashlytics
  - mobile agent
  - android
  - ios
  - apps

# Relevant documentation for this quickstart
documentation:  
  - name: Instrument your mobile application with New Relic
    url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring/
    description: How to instrument your mobile application with New Relic

  - name: Adding a dashboard
    url: https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/#get-started
    description: How to add a dashboard to New Relic

# References to dashboards by file path, the first entry references a dashboard located at `dashboards/example-dashboard`
# For more information on dashboard definitions, see the section below.
dashboards:
  - mobile-crash-analytics

# References to install plan IDs (**NOTE**: Not the file path)
# The Ordering of installPlans is important as it sets the order of installation.
installPlans:
  - mobile-dashboard-install