id: jumpstart
displayName: Jumpstart
description: |
  The Jumpstart quickstart is a quick and easy way to see how to get started building a quickstart for partner companies.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/new-relic-quickstarts-overview/
