id: test-data-source

displayName: Test Data Source

description: |
  test

install:
  primary:
    nerdlet:
      nerdletId: test.test-nerdlet
      nerdletState: 
        test_state: test
      requiresAccount: true
  fallback:
    link:
      url: https://newrelic.com


keywords:
  - test
  - keyword2

categoryTerms: 
  - test
  - term2
