id: otel-jenkins-integration
displayName: Jenkins
description: |
  Jenkins is an open source automation server which enables developers around the world to reliably build, test, and deploy their software.
icon: logo.svg
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot/
keywords:
  - jenkins
  - opentelemetry
  - otel
  - pipelines
  - NR1_addData
  - NR1_sys
categoryTerms:
  - open source monitoring
