id: argocd

displayName: ArgoCD 
description: |
  Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.

icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 03b4a3b9-3a59-4603-91dd-6b0ced1d62de
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration

keywords:
  - argocd
  - helm
  - kubernetes
  - k8s
  - cd
  - continuous deployment
  - argo
  - newrelic partner
categoryTerms:
  - newrelic partner


