id: argocd

displayName: ArgoCD
description: |
  Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes.

icon: logo.png
install:
  primary:
    nerdletId: "nr1-install-newrelic.nr1-install-newrelic",
    nerdletState:
      path: "guided",
      env: "kubernetes",
      activeComponent: "VTSOKubernetes",
      activeEnvironment: "kubernetes"
  fallback:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-update-or-uninstall-your-prometheus-openmetrics-integration

keywords:
  - argocd
  - helm
  - kubernetes
  - k8s
  - cd
  - continuous deployment
  - argo
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
