
slug: activemq
description: |
  ## Comprehensive monitoring quickstart for ActiveMQ
  New Relic Detects your ActiveMQ metrics like queues, brokers,  producers, consumers, garbage collection rate, heap memory usage and more. 

  ## Why monitor ActiveMQ?
  Apache ActiveMQ is a fault-tolerant, scalable messaging system used to build real-time data pipelines. ActiveMQ also supports replications natively, and can help build streaming applications that run inside production environments.

  Leveraging a ActiveMQ monitoring tool to monitor data replication, retention, and issues like consumer lag is important. New Relic’s ActiveMQ quickstart lets you look at performance metrics and inventory data on a real-time basis, create your own custom dashboard with charts and queries, and create alert policies. 


  ## What’s included in this quickstart?
  New Relic’s performance monitoring provides instant observability out-of-the-box.

  This quickstart includes:
  - Easily monitor and identify when your ActiveMQ nodes are underperforming.
  - Interactive dashboards helping you track brokers, messages per sec, broker connections, memory usage, storage usage and more.
  - Monitors you about traffic usage and informs you about message processing-time degradation. 


summary: |
  Monitor the performance metrics of your Apache ActiveMQ instances in real-time with New Relic APM.
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: ActiveMQ
documentation:
  - name: ActiveMQ integration documentation
    description: |
      Monitor the performance metrics of your Apache ActiveMQ instances in real-time with New Relic APM.
    url: >-
      https://docs.newrelic.com/
keywords:
  - activemq
  - jmx monitoring
  - apache
installPlans:
  - activemq-integration
dashboards:
  - activemq
alertPolicies:
  - activemq
