id: 73de5982-8f59-4d2d-a90a-4838414d3304
slug: aws-mq
description: |-
  What is AWS MQ?

  Message brokering service for Apache ActiveMQ managed by AWS.

  ### Get started!

  Start monitoring AWS MQ by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS MQ documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info 

  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-mq-integration/) to learn more about New Relic monitoring for AWS MQ.

summary: Monitor AWS MQ by connecting AWS to New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: AWS MQ
documentation:
  - name: AWS MQ installation docs
    description: Monitor AWS MQ by connecting AWS to New Relic
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-mq-integration/
keywords:
  - aws
  - amazon web services
  - messaging
  - queue

installPlans:
  - aws-cloudwatch-metric-streams
dashboards:
  - aws-mq