name: servicenow-notifications

title: ServiceNow Notifications

description:  |
  
  ServiceNow is a software that helps companies manage digital workflows for enterprise operations.

  Check out our documentation to set up a ServiceNow notification channel and provide fast and consistent ways for the right personnel to be notified about incidents

summary: |
  Send your New Relic alerts to ServiceNow

logo: logo.png

level: New Relic

authors:
  - Matan Moser (New Relic)
  - Ismail Azam (New Relic)

keywords:
  - servicenow
  - notifications
  - AIOps
  - Incident Intelligence
  - Destinations

documentation:
  - name: ServiceNow notification integration docs
    description: |
      Integrate New Relic with ServiceNow Incident-Management and automatically create and update incidents.
    url: >-
      https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/notification-integrations/#servicenow
