id: d42f2744-3d69-4860-97af-ec9e75885038
name: full-stack-observability
title: Full Stack Observability

description: |
  Set of dashboards with data from all New Relic Products, giving you Full Stack Observability over Metrics, Events, Logs and Traces.

level: New Relic
icon: icon.jpeg
logo: logo.png
website: https://www.newrelic.com/

authors:
  - New Relic
  - Samuel Vandamme

installPlans:
  - guided-install

keywords:
  - full stack observability
