slug: google-cloud-spanner-latency
description: |-
  ## What is Google Cloud Spanner?

  Globally-distributed relational database service built for the cloud. Add
  schemas, write and modify data, and run queries.


  ### Get started!
  
  The metric data available with this integration pairs alongside the [CPU monitoring integration](https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-spanner-monitoring-integration/) for full stack observability on your cloud spanner intance. This integration focuses on DB Queries, latency timing, and other core metrics on your Google Cloud Spanner instance.
  
  ### About this quickstart

  This integration gives you visibility into the following:

  - Slow query count
  - Commit latency
  - Average Bytes
  - Average lock wait
  - Average cpu seconds
  - Average rows

summary: |-
  Monitor Google Cloud Spanner latency metrics by using prometheus exporter
icon: logo.svg
level: community
authors:
  - New Relic
title: Google Cloud Spanner (latency monitoring)
documentation:
  - name: Example Prometheus exporter
    description: |
      Example google spanner prometheus exporter
    url: >-
      https://github.com/architjugran/example-cloudspannerreceiver
  - name: Prometheus New Relic docs
    description: |
      Use the prometheus exporter to send Metrics to New Relic
    url: >-
      https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/
keywords:
  - gcp
  - google cloud platform
  - database
  - newrelic-partner

installPlans: 
  - cloud-spanner

Dashboard: gcp-cloud-spanner
