
# Name of the pack
name: Consul

# Description of the pack
description: |+
  Official New Relic pack for Consul
  Use this pack together with the New Relic Consul On Host Integration to get insight into the performance of your Consul instances.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://www.consul.io/

# Authors of the pack
authors:
  - New Relic
  - Daniel Gola

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: consul
