id: confluent-cloud

displayName: Confluent Cloud - Managed Kafka

# Long-form description of the quickstart (required)
description: |
  ## About Confluent

  Confluent makes it easy to connect your apps, data systems, and entire organization with real-time data flows and processing.

  ## About Confluent Cloud

  Confluent Cloud is a fully managed, cloud-native service for connecting and processing all of your data, everywhere it’s needed.
  
  ## About this quickstart

  Observability for Confluent Cloud's fully managed service for Apache Kafka on New Relic delivered using the OpenTelemetry Collector

  For more information check out our website at [confluent.io](https://www.confluent.io/)

icon: logo.png

install:
  primary:
    link:
       url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-kafka-confluentcloud

# Keywords for filtering / searching criteria in the UI
keywords:
  - Confluent
  - Confluent Cloud
  - Metrics
  - OTEL
  - OpenTelemetry
  - OTelCol
  - OpenTelemetry Collector
  - Collector
  - newrelic partner

categoryTerms:
  - opentelemetry
  - newrelic partner
