id: ad40ccc2-f7ef-44bf-b961-07813088fce0

# Name of the quickstart (required)
name: chef

# Displayed in the UI (required)
title: Chef

# Long-form description of the quickstart (required)
description: |
  Chef is a configuration management tool written in Ruby and Erlang.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Chef is a configuration management tool written in Ruby and Erlang.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - automation
  - devops
  - sre
  - gitops

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
documentation:
  - name: Chef installation docs
    description: Chef is a configuration management tool written in Ruby and Erlang.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/config-management-tools/configure-new-relic-infrastructure-using-chef
  - name: Chef Supermarket
    description: Chef Supermarket page for the New Relic Chef Recipe
    url: >-
      https://supermarket.chef.io/cookbooks/newrelic-infra

# Content / Design
logo: logo.svg
website: https://supermarket.chef.io/cookbooks/newrelic-infra
