id: flutter-ios
displayName: Flutter iOS
description: |
  Instrument and monitor your Flutter iOS app with New Relic’s iOS and Flutter Agent. Analyze your performance data (Errors, Application Crashes, App Launches and App Installations) to diagnose, improve, and optimize your code.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application/

keywords:
  - flutter
  - flutter ios application
  - ios agent
  - flutter agent