id: flutter-ios
displayName: Flutter iOS
description: |
  Instrument and monitor your Flutter iOS application with the New Relic’s iOS and flutter agent. Analyze your performance data (Errors, Application crashes, App launches, HTTP response and Network failures) in view of the best code diagnosis, improvement, and optimization.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application/

keywords:
  - flutter
  - flutter ios application
  - ios agent
  - flutter agent