id: c4512294-8f81-4efa-8f28-6c1db28d288c
# Name of the quickstart (required)
name: speedscale

# Displayed in the UI (required)
title: Speedscale

# Long-form description of the quickstart (required)
description: |
  Export traffic replay performance data collected and analyzed by Speedscale so it can be viewed in the New Relic console.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Export traffic replay performance data collected and analyzed by Speedscale so it can be viewed in the New Relic console.

# Support level: New Relic | Verified | Community (required)
level: Verified

# Authors of the quickstart (required)
authors:
  - Speedscale Inc.

# Keywords for filtering / searching criteria in the UI
keywords:
  - traffic
  - replay
  - simulate
  - report

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - third-party-speedscale-integration

documentation:
  - name: Speedscale Installation Docs
    url: docs.speedscale.com
    description: The only prerequisite is to obtain your New Relic account id and insights insert key.

# Content / Design
logo: logo.svg
website: https://speedscale.com
