id: ad5affab-545a-4355-ad48-cfd66e2fbf00

# Name of the pack
name: Apache

# Description of the pack
description: |+
  # Complete Apache Monitoring Kit
  ## Understanding Apache
  The Apache HTTP Server is a free and open-source, secure, efficient, and extensible HTTP web server
  for the Windows and UNIX operating systems. It has been around since the mid-90s, and it is the most popular web server available on the internet.

  ## Why monitor Apache HTTP Server?
  Succinctly put, web servers are computers that run web applications. So given the essentiality of a
  webserver to an IT infrastructure, it is paramount to monitor its operations to ensure continual
  optimal performance. Their performance level is crucial to optimizing uptimes for web applications.

  ## What should you look for in an Apache HTTP Server Monitor?
  Any rudimentary Apache dashboard must provide developers with enough information to ascertain
  that a web server promptly accepts requests and serves them with accurate responses. However, an
  ideal Apache performance monitoring tool must provide more comprehensive details. A great
  Apache monitor offers developers critical information to help them paint a complete picture of a web server's performance. Such data includes error analytics, host-related resource metrics,
  throughput metrics, latency metrics, resource utilization metrics, and activity metrics.

  ## What’s Included?
  Our kit offers ready to use dashboards including:
  - servers reporting
  - total requests per second
  - requests per second by server
  - worker status, and more

  ## What makes New Relic's kit unique?
  In designing our kit, our team reflected on the critical design attributes a monitor must embody to be considered adequate and efficient. To that end, they deduced that firstly, a monitor must feature an intuitive design that allows developers to look up their preferred performance-related data quickly.
  Secondly, it must also feature an efficient issue resolution process. To realize an implementation
  representative of these inferences, we developed a kit that combines practicality and usability to
  achieve an unprecedented user experience in performance tracking.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.svg
website: https://httpd.apache.org/

# Authors of the pack
authors:
  - New Relic
  - Jakub Kotkowiak

documentation:
  - name: Apache monitoring integration
    description: >-
      Free and open-source cross-platform web server software, released under the terms of Apache License 2.0.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration/
  - name: Apache HTTP client
    description: >-
      Java package implementing the client side of the most recent HTTP standards and recommendations.
    url: https://docs.newrelic.com/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent/
  - name: Apache Zookeeper
    description: >-
      Service offering a hierarchical key-value store that provides distributed configuration, synchronization, and naming registries.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/zookeeper-monitoring-integration/

installPlans:
  - infra-agent-targeted
  - apache-integration
keywords:
  - infrastructure
  - http
  - web
  - server
  - featured


