id: vsphere-integration
displayName: VMware vSphere
description: The VMware vSphere integration helps you understand the health and performance of your vSphere environment.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration/
icon: logo.svg
