id: synthetics-user-step-execution
displayName: Synthetics User Step Execution
description: |
  Zero code Synthetics monitor building
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
icon: logo.svg
