---

extends: relaxed

ignore: |
  **/node_modules/
  **/utils/__tests__/mock_files/

rules:
  colons: disable
  empty-lines: disable
  indentation: disable
  line-length: disable
  new-line-at-end-of-file: disable
  trailing-spaces: disable
