id: third-party-netlify-builds
name: Netlify Builds
title: Netlify Builds quickstart
description: |
  Netlify is an all-in-one platform for automating modern web projects. Replace your hosting infrastructure, continuous integration, and deployment pipeline with a single workflow. Integrate dynamic functionality like serverless functions, user authentication, and form handling as your projects grow.

target:
  type: integration
  destination: cloud

install:
  mode: link
  destination:
    url: https://www.npmjs.com/package/@newrelic/netlify-plugin#installation
