id: apache-flink
displayName: Apache Flink monitoring
description: |
  With our Apache Flink dashboard, you can easily track your logs, keep an eye on your instrumentation sources, and get an overview of uptime and downtime for all your applications' instances. Built with our infrastructure agent and our Prometheus OpenMetrics integration, Apache Flink dashboards take advantage of OpenMetrics endpoint scraping, so you can view all your most important data in one place.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-apache-flink/
icon: logo.png
