id: apache-flink
displayName: Apache Flink monitoring
description: |
  With our Apache Flink dashboard, you can track your logs, see your instrumentation sources, and get an overview of uptime and downtime for all your applications’ instances. You can view all your most important data in one place.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-apache-flink/
icon: logo.png
