id: akamai
displayName: Akamai Datastream2
description: |
  ## About Akamai
    
  Akamai Technologies is a leading content delivery network (CDN), cybersecurity, and cloud service provider.
  
  ### DataStream 2

  DataStream 2 captures performance and security logs from your delivery properties and streams them in near real-time to provide complete monitoring.

  For more information check out our [datastream2 docs](https://techdocs.akamai.com/datastream2/docs)

icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: cb995039-39d8-44d9-97c3-58174a1337f2
      requiresAccount: true
  fallback:
    link:
      url: https://techdocs.akamai.com/datastream2/docs/stream-new-relic
keywords:
  - akamai
  - logs
  - network
  - security
  - cdn
  - featured
  - newrelic partner
  - datastream
categoryTerms:
  - newrelic partner
  - logs
  - network
