# Name of the quickstart (required)
name: mlops-comet

# Displayed in the UI (required)
title: Comet

# Long-form description of the quickstart (required)
description: |
  [Comet](https://www.comet.ml/site/) is an MLOps platform that extends full stack observability to machine learning models, and allows you to establish production performance baselines based on model performance. The Comet integration allows you to integrate machine learning metrics with New Relic, so you can continuosly monitor your data across the full machine learning lifecycle. This helps ensure optimal model performance, and helps you achieve better business outcomes.

  Use New Relic's Comet integration to get data and insights that help you build better, more accurate machine-learning models, while also improving productivity, collaboration, and visibility across your team.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Comet’s integration with New Relic One extends infrastructure observability to include your ML models in production and their performance baselines established in training, so you can build better models faster.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Jacques Verre

# Keywords for filtering / searching criteria in the UI
keywords:
  - mlops
  - ml-ops
  - model ops
  - model-ops
  - ml
  - machine learning
  - ai
  - comet
  - observability
  - monitoring
  - data monitoring

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - comet-mlops

documentation:
  - name: Comet Docs
    url: https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/mlops-integrations/comet-mlops-integration/
    description: Documentation about Integrating Comet with New Relic

# Content / Design
logo: logo.png
website: https://www.comet.ml/site
