# Name of the quickstart (required)
name: CircleCI

# Displayed in the UI (required)
title: CircleCI Quickstart

# Long-form description of the quickstart (required)
description: |
The world’s best software teams use CircleCI to deliver quality code with confidence. As the largest continuous integration and delivery (CI/CD) platform, CircleCI empowers engineers to seamlessly take ideas to execution, at scale. Every feature of our platform is built to fine-tune the entire development process from start to finish.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  This integration allows users to view analytical data about their CircleCI jobs within the New Relic monitoring stack.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - New Relic
  - Joseph Counts

# Keywords for filtering / searching criteria in the UI
keywords:
  - newrelic partner
  - devops
  - circleci
  - circle
  - ci/cd

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - third-party-circleci

documentation:
  - name: CircleCi Webhooks documentation
    url: https://circleci.com/docs/2.0/webhooks/
    description: CircleCi webhooks documentation

# Content / Design
logo: logo.png
website: https://circleci.com/
