id: synthetics-availability
displayName: Synthetics Availability (Ping)
description: Availabilty or Ping monitors are the simplest type of monitor. They simply check to see if an application is online.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
icon: logo.svg
