id: unix

displayName: Unix

description: |
  The Unix monitoring integration allows for system-level monitoring of AIX,
  Linux, macOS, Solaris/SunOS and other Unix-based servers.

logo: logo.svg

install:
  primary:
    nerdlet: nr1-install-newrelic.quickstart-installation-plan
    nerdletState:
      quickstart_id: 9fdfa9b9-4a83-47e6-a8d5-b23cc05b653a
  requiresAccount: true
  secondary:
    link: https://docs.newrelic.com/docs/integrations/host-integrations/open-source-host-integrations-list/unix-monitoring-open-source-integration

keywords:
  - os
  - operating system

categoryTerms:
  - os
