id: unix
displayName: Unix
description: |
  The Unix monitoring integration allows for system-level monitoring of AIX,
  Linux, macOS, Solaris/SunOS and other Unix-based servers.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 9fdfa9b9-4a83-47e6-a8d5-b23cc05b653a
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/integrations/host-integrations/open-source-host-integrations-list/unix-monitoring-open-source-integration
keywords:
  - os
  - operating system
categoryTerms:
  - os
