id: 71e1b882-ce4e-4037-b8f1-997d9e317ddd
name: roku
description: Build applications that deliver high-quality video to the Roku platform.
summary: Build applications that deliver high-quality video to the Roku platform.
icon: icon.svg
logo: logo.svg
level: New Relic
authors:
  - New Relic Labs
title: Roku
documentation:
  - name: Roku installation docs
    description: Build applications that deliver high-quality video to the Roku platform.
    url: >-
      https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/roku/roku-open-source-video-agent/
keywords:
  - nrlabs
  - nrlabs-data
  - video
  - tracker
  - roku
