slug: aws-billing-budgets
title: AWS billing budgets
description: |-
  ## What is AWS Billing?

  The AWS Billing console provides features to manage and report your AWS cost and usage based on user-defined methods. With this, you can easily understand your AWS spending, pay invoices, analyze and control costs, manage billing preferences and tax settings, and access other cloud financial management services.

  ### New Relic AWS Billing features

  The New Relic AWS Billing integration empowers you with an [AWS Billing integration](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-billing-monitoring-integration) that collects AWS financial data and splits it into two groups, billing costs and billing budgets, to make it easier for your team to gain cost visibility.

  ### Why monitor AWS Billing with New Relic?

  With our AWS Billing integration, you can gain visibility into all of your financial data. Our integration aggregates data from different sub-accounts and services and looks at your budgets in actual and forecasted spend. The best part? It’s all in one place. 
  
  Start ingesting your AWS billing data today and visualize your AWS billing metrics in real-time. 
summary: |-
  Monitoring AWS Billing is critical to effectively track AWS cost and usage. Download the New Relic AWS Billing quickstart to proactively monitor AWS financial data including AWS billing metrics and AWS budget metrics.
level: New Relic
authors: 
  - New Relic
keywords:
  - aws
  - amazon web service
  - billing
  - budgets
  - costs
documentation:
  name: AWS Billing (budgets) installation docs
  url: >-
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-billing-monitoring-integration
  description: |
      Monitor AWS Billing by connecting AWS to New Relic.
icon: logo.svg
dashboards: 
  - aws-billing-budgets
  - aws-billing-costs
installPlans:
  - aws-infrastructure-monitoring
