# Name of the quickstart (required)
name: terraform

# Displayed in the UI (required)
title: Terraform

# Long-form description of the quickstart (required)
description: |
  Terraform is a popular infrastructure-as-code software tool built by HashiCorp.
  You use it to provision all kinds of infrastructure and services, including New Relic entities, dashboard, alerts and synthetics.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Terraform is a popular, infrastructure-as-code software tool built by HashiCorp.
  You use it to provision all kinds of infrastructure and services, including New Relic entities, dashboard, alerts and synthetics.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - automation
  - devops
  - sre
  - gitops

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
documentation:
  - name: Getting started with New Relic and Terraform
    description: |
      In this guide, you learn how to set up New Relic alerts with Terraform.
    url: >-
      https://developer.newrelic.com/terraform/get-started-terraform/
  - name: New Relic Provider
    description: Terraform documentation for the New Relic Provider
    url: >-
      https://registry.terraform.io/providers/newrelic/newrelic/latest/docs
  - name: Github repository
    description: Github repository for the New Relic Provider.
    url: >-
      https://github.com/newrelic/terraform-provider-newrelic

# Content / Design
logo: logo.svg
website: https://registry.terraform.io/providers/newrelic/newrelic/latest/docs
