id: synthetics-page-link-crawler
displayName: Synthetics Page Link Crawler
description: Monitoring website links is crucial to ensure that you detect broken links and resolve outages swiftly. Download the New Relic Synthetic Link Crawler quickstart to start monitoring your websites for broken links.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
icon: logo.svg
