slug: aws-appsync
title: AWS appsync
description: |-
  ## What is AWS AppSync?

  Fully managed serverless GraphQL service for real-time data queries,
  synchronization, communications and offline programming features.


  ### Get started!

  Start monitoring AWS AppSync by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS AppSync documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-appsync-monitoring-integration) to learn more about New Relic monitoring for AWS AppSync.
summary: |-
  Monitor AWS AppSync by connecting AWS to New Relic
level: New Relic
authors: 
  - New Relic
keywords:
  - aws
  - amazon web service
  - api
documentation:
  name: AWS AppSync installation docs
  url: >-
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-appsync-monitoring-integration
  description: |
      Monitor AWS AppSync by connecting AWS to New Relic.
icon: logo.svg
dashboards:
  - aws-appsync
installPlans:
  - aws-cloudwatch-metric-streams
