id: d0e829a6-ede4-4933-9065-9f0c56f8aa7e
# Name of the pack (required)
name: mlops-dagshub

# Displayed in the UI
title: DagsHub

# Long-form description of the pack (required)
description: |
  DagsHub description...

# Displayed in search results and recommendations. Summarizes a packs functionality.
summary: |
  DagsHub summary...

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the pack (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - mlops
  - ml
  - ai
  - dagshub
  - machine-learning
  - machine learning

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - dagshub-mlops

documentation:
  - name: DagsHub Docs
    url: https://docs.newrelic.com/docs/integrations/mlops-integrations/dagshub-mlops-integration/
    description: Documentation on the workings of the DagsHub integration

# Content / Design
icon: icon.svg
logo: logo.svg
website: https://dagshub.com/
