name: battlesnake

title: Battlesnake

# TODO: add final copy
summary: |
  Battlesnake is a multi-player programming game played by developers all over the world. All you need to play is a live web server that implements the Battlesnake API.

# TODO: add final copy
description: |
  Battlesnake is a multi-player programming game played by developers all over the world. All you need to play is a live web server that implements the Battlesnake API.

level: New Relic

authors:
  - New Relic
  - Zack Stickles

installPlans:
  - battlesnake

icon: icon.png

website: https://play.battlesnake.com
