

slug: flutter-android
description: |
  ## Comprehensive monitoring quickstart for Flutter Android
  
  Monitor your Flutter applications, and analyze performance bottlenecks while operating in a live development environment. Visually monitor your web user experience across the world with your application rendition via the dashboard.
  
  ## Why monitor Flutter Android?
  Monitoring app performance helps you to take a preventative approach to enhance quality rather than waiting for a crash, issue, or user complaint to occur. The Newrelic Flutter APM tool allows you to track important metrics including Apdex ratings, UI hangs, network timeouts and issues, slow launches, tracking custom traces, and more.
   
  By prioritizing active issues and marking errors as corrected, you may optimize the process once you have a comprehensive picture of all releases. Find out which version the problem first appeared in, merge duplicates, and assess whether anything may get worse in a later release. Add commit information to send deploy emails instantly and suggest an owner for each application error.
  
  ## What’s included in this quickstart?
  New Relic's Android and Flutter agents captured the metrics out of the box:
  - Be alerted on critical issues affecting your flutter android application.
  - Dashboards (Error rate, App launches, App installations, App crashes and more).
  - Monitor Flutter Dart exceptions and Errors.
  - Monitor HTTPs response, HTTPs errors and Mobile events.
  
  Install and start monitoring your data today! 
  
summary: |
  Instrument and monitor your Flutter Android application with the New Relic’s Android and Flutter agents. Analyze your performance data (Errors, Application crashes, App launches, HTTPs response and Network failures) in view of the best code diagnosis, improvement, and optimization.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Flutter Android
documentation:
  - name: Flutter Android integration documentation
    description: |
      Monitor the performance metrics of your Flutter Android application instances in real-time with New Relic's Android and Flutter agents.
    url: >-
      https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-flutter/monitor-your-flutter-application/
keywords:
  - flutter
  - flutter android application
  - android agent
  - flutter agent
dashboards:
  - flutter-android
alertPolicies:
  - flutter-android
dataSourceIds:
  - flutter-android