id: jmeter
displayName: JMeter
description: |
  Apache JMeter is open source software, a Java application designed to load test functional behavior and measure performance. It was originally designed for testing Web Applications but has since expanded to other test functions.
  The link to JMeter plug-in provided enables you to send test results to New Relic.
  This quickstart allows users to monitor JMeter tests inside New Relic and observe test results in the context of instrumented applications.
  The JMeter quickstart includes:
  ## a dashboard
    where users can easily monitor:
    - Thread Group Details
    - HTTP Responses
    - Summary Report
    - View Results in Table
  ## alert conditions
    where users are notified on:
    - Test Error Rate
    - 90th Percentile Latency
icon: logo.png
install:
  primary:
    link:
      url: https://github.com/darrensmithwtc/jmeter-backend-newrelic
keywords:
  - jmeter
  - performance
  - load
  - stress
  - functional
  - testing web application
categoryTerms:
  - open source testing