slug: aws-ecs
title: AWS ECS
description: Fully managed container orchestration service built on AWS with a focus on security, reliability, and scalability.
summary: Monitor AWS ECS by connecting AWS to New Relic
level: New Relic
authors:
  - New Relic
keywords:
  - aws
  - amazon web service
  - containers
  - infrastructure
documentation:
  - name: AWS ECS/ECR installation docs
    description: |
      Monitor AWS ECS/ECR by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-ecsecr-monitoring-integration/
icon: logo.svg
dashboards: aws-ecs
installPlans:
  - aws-cloudwatch-metric-streams
