
# Name of the pack
name: Gatsby Build

# Description of the pack
description: |+
  The template pack allows you to get visibilility into the build time of your Gatsby Site,
  using Open Telemetry to collect each step as Trace Data

# Support level: New Relic | Verified | Community
level: New Relic

# Design
icon: icon.jpeg
logo: logo.png

# Authors of the pack
authors:
  - New Relic
  - Ruairi Douglas

references:
  - type: operating-system
    name:
    - linux
    - windows



