id: aws-cloudfront-logs
displayName: Amazon Cloudfront Web Logs
description: |-
  ## What is Amazon CloudFront?


  Speeds up the distribution of web content served from Amazon Web Services.


  ### Get started!


  Start monitoring Amazon CloudFront by sending your Amazon Cloudfront Web Logs
  to New Relic. 


  Check out our Amazon CloudFront documentation to instrument your cloud service
  and manage the stability, scalability, and reliability of your systems with
  New Relic's Log monitoring capabilities.


  ### More info


  Check out the
  [documentation](https://docs.newrelic.com/docs/logs/forward-logs/cloudfront-web-logs/)
  to learn more about New Relic monitoring for Amazon CloudFront.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: fb4c4acc-e341-4b87-9bb1-5f98b9cc9310
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/logs/forward-logs/cloudfront-web-logs/
keywords:
  - aws
  - cloudfront
  - amazon web services
  - logs
  - security
  - cdn
  - featured
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
  - logs
