id: mariadb

displayName: MariaDB

description: |
  MariaDB is a community-developed, commercially supported fork of the MySQL
  relational database management system.

logo: logo.svg

install:
  primary:
    nerdlet: nr1-install-newrelic.quickstart-installation-plan
    nerdlet_state:
      quickstart_id: 0919c174-0ce5-4b34-a5c0-255986ff9706
      requires_account: true
  secondary:
    link: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mysql-monitoring-integration

keywords:
  - infrastructure
  - database

categoryTerms:
  - infrastructure
