# Name of the quickstart (required)
name: pulumi

# Displayed in the UI (required)
title: Pulumi

# Long-form description of the quickstart (required)
description: |
  Pulumi is a popular infrastructure-as-code software tool.
  You use it to provision all kinds of infrastructure and services, including New Relic entities, dashboard, alerts and synthetics.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Pulumi is a popular infrastructure-as-code software tool.
  You use it to provision all kinds of infrastructure and services, including New Relic entities, dashboard, alerts and synthetics.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Pulumi

# Keywords for filtering / searching criteria in the UI
keywords:
  - automation
  - devops
  - sre
  - gitops

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
documentation:
  - name: Getting started with New Relic and Pulumi
    description: |
      In this guide, you learn how to set up New Relic alerts with Pulumi.
    url: >-
      https://www.pulumi.com/registry/packages/newrelic/
  - name: New Relic Package
    description: Pulumi documentation for the New Relic Package
    url: >-
      https://www.pulumi.com/registry/packages/newrelic/api-docs/
  - name: Github repository
    description: Github repository for the New Relic Package.
    url: >-
      https://github.com/pulumi/pulumi-newrelic

# Content / Design
logo: logo.svg
website: https://www.pulumi.com/registry/packages/newrelic/
