id: red-hat-openshift
displayName: Red Hat OpenShift
description: |
  Red Hat OpenShift is a hybrid cloud, enterprise Kubernetes application
  platform.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/
icon: logo.svg
