name: pkg-errors
title: pkg/errors
description: |
  Wrap pkg/errors errors to improve stack traces and error class information
level: Community
authors:
  - New Relic
keywords:
  - golang
  - errors
installPlans:
  - setup-go-agent
documentation:
  - name: Go agent compatibility and requirements
    url: >-
      https://docs.newrelic.com/docs/agents/go-agent/get-started/go-agent-compatibility-requirements/

