
# Name of the pack
name: Template pack

# Description of the pack
description: |+
  The template pack allows you to get visibilility into the performance and available of your example service and dependencies.
  Use this pack together with the mock up integrations.

# Support level
level: New Relic | Community Plus | Community

# Design
icon: icon.jpeg
logo: logo.png # When this is not set to a filepath or url, we look for logo.jpeg|jpg|png|gif?
website: https://www.newrelic.com

# Authors of the quickstart
authors:
  - New Relic

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: nginx
  - type: prometheus
    url: https://github.com/nginxinc/nginx-prometheus-exporter

# References to other packs (optional)
# References are grouped by the type: operating-system, database, webserver, queue, ..
# The reference under the type is a at least one system, so at least one operating-system, database, ..
references:
  - type: operating-system
    name:
    - linux
    - windows
  - type: database
    name:
    - mysql
  - type: application # or nerdlet? or nerdpack? or ?
    name: cloud-optimiser



