
# Name of the pack
name: Template pack

# Support level
level: New Relic | Community Plus | Community

# Design
icon: icon.jpeg
logo: logo.png # When this is not set to a filepath or url, we look for logo.jpeg|jpg|png|gif?
website: https://www.newrelic.com

# References to other packs (optional)
# References are grouped by the type: operating-system, database, webserver, queue, ..
# The reference under the type is a at least one system, so at least one operating-system, database, ..
references:
  - type: operating-system
    name:
    - linux
    - windows
  - type: database
    name:
    - mysql
  - type: application # or nerdlet? or nerdpack? or ?
    name: cloud-optimiser

# Instrumentation (optional)
instrumentation:
  - type: newrelic-ohi
    name: nginx
  - type: prometheus
    url: https://github.com/nginxinc/nginx-prometheus-exporter

