
# Sets the URL name of the quickstart on public I/O (required)
slug: sybase

# Displayed in the UI (required)
title: Sybase

# Long-form description of the quickstart (required)
description: |-
  Check out [nri-db](https://github.com/newrelic-experimental/nri-db) to learn more about New Relic monitoring for Sybase.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Monitor SAP Adaptive Server Enterprise (Sybase)

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - New Relic
  - Peter Nguyen

# Keywords for filtering / searching criteria in the UI
keywords:
  - sybase
  - sap
  - ase
  - adaptive server enterprise

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - sybase-integration

dashboards:
  - sybase

# Documentation references
documentation:
  - name: New Relic Integration - Database
    url: https://github.com/newrelic-experimental/nri-db
    description: Monitor SAP Adaptive Server Enterprise (Sybase)

# Content / Design
icon: logo.svg
website: https://www.newrelic.com
