slug: resmo
description: |
  ## What is Resmo?
   Resmo is a tool to help you understand your environment with normalized assets like users, devices or databases, deep dive with SQL, graphs and relations, and secure your entire environment.
  
  ### How this integration works

  Once you sign up to Resmo, you can easily integrate your account with New Relic using an API key. Resmo uses an API to do the initial polling and collect existing resources. Then, we receive resource changes and updates in real-time by regular polling.
  
  ### What does this integration offer
  
  With this integration you can:
  - Gather and monitor all your New Relic assets on a single platform. 
  - Query your New Relic dashboards, accounts, alert policies, API keys, and more. 
  - Set up rules to continuously assess your New Relic resources. 
  - Set up and receive rule notifications based on your New Relic resource configurations.

    
summary: |
  Resmo can help you to understand your environment with normalized assets
icon: logo.svg
level: New Relic
authors:
  - New Relic
  - Resmo
title: Resmo
documentation:
  - name: Resmo installation docs
    description: Integrate your Resmo account with New Relic using an API key.
    url: >-
      https://docs.resmo.com/product/integrations/new-relic-integration
keywords:
  - resmo
  - newrelic partner
  - assets
  - rules
  - notifications
  - resource configurations

