slug: mobile-quickstart

# Used as the display name for the quickstart
title: Mobile dashboard quickstart

description: |
  A dashboard for basic mobile metrics such as active users, installs and error rate.

summary: |
  A dashboard for basic mobile metrics such as active users, installs and error rate.

# Possible values: New Relic | Verified | Community
# Please consult with pull request reviewers if you think your quickstart should have a support level other than "Community"
level: Community

authors:
  - Víctor Pérez

keywords:
  - dashboard
  - mobile
  - android
  - ios
  - apps

# Relevant documentation for this quickstart
documentation:
  - name: Installation docs
    url: https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/#get-started
    description: How to add a dashboard to New Relic

# An icon or logo for the quickstart
icon: icon.png

# References to dashboards by file path, the first entry references a dashboard located at `dashboards/example-dashboard`
# For more information on dashboard definitions, see the section below.
dashboards:
  - mobile

# References to install plan IDs (**NOTE**: Not the file path)
# The Ordering of installPlans is important as it sets the order of installation.
installPlans:
  - mobile-dashboard-install