
slug: lighttpd
description: |
  ## Comprehensive monitoring quickstart for Lighttpd

  Lighttpd is an open-source web server designed for high-performance situations while staying standards-compliant, secure and adaptable.

  ### Why monitor Lighttpd?

  Lighttpd monitoring provides developers with important information to help them construct a complete picture of a web server's performance. This data comprises error analytics, network in bytes and packets, host-related resource metrics, throughput, latency, server performance, and activity metrics.

  ### What’s included?

  The Lighttpd monitoring quickstart from New Relic provides immediate full-stack observability:
  - Alerts including high CPU utilization, high memory usage, transaction error.
  - Dashboards (Throughput, Error rate, Logs, Uptime, busy server, networks, requests per second and more).
  - Actively monitor where you should focus your efforts and fix potential issues as soon as possible.

summary: |
  Monitor and verify your Lighttpd processes with our Infrastructure agent and Prometheus open metric integration. Analyze and capture the performance data right out of the box. 
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Lighttpd
installPlans:
  - lighttpd
dashboards:
  - lighttpd
alertPolicies:
  - lighttpd
documentation:
  - name: Lighttpd
    description: |
      Integrate your Lighttpd processes with our Infrastructure agent and Prometheus open metric integration to collect data and send it to New Relic.
    url: >-
      https://docs.newrelic.com/
keywords:
  - lighttpd
  - web server
  - web
  - server
