
# Name of the pack
name: Varnish

# Description of the pack
description: |+
  Official New Relic pack for Varnish
  Use this pack together with the New Relic Varnish On Host Integration to get insight into the performance of your Varnish instances.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://varnish-cache.org/

# Authors of the quickstart
authors:
  - New Relic
  - Jakub Kotkowiak

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: varnish
