id: codestream
displayName: CodeStream 
description: |
  New Relic CodeStream supercharges development workflows by putting collaboration tools in your IDE. It supports pull requests from GitHub, BitBucket and GitLab, issue management from Jira, Trello, Asana and 9 others, observability from New Relic One and Pixie, and provides code discussion that ties it all together, integrated with Slack, MS Teams, email, and in-editor notifications.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 29bd9a4a-1c19-4219-9694-0942f6411ce7
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/codestream/start-here/new-relic-codestream-quick-start/ 
keywords: []
categoryTerms: []
