id: wayscript
displayName: WayScript
description: |
  WayScript is an Internal Developer Platform (IDP) that enables scalable, single click development environments. Connect your environments to New Relic in minutes.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: todo-wait-for-nerdlet-id
      nerdletState:
        quickstart_id: todo-wait-for-quickstart-id
      requiresAccount: true
  fallback:
    link:
      url: https://wsxdocs.wayscript.com/quickstart
keywords:
  - wayscript
  - idp
  - internal developer platform
  - newrelic partner
  - featured
categoryTerms:
  - newrelic partner
