id: wayscript
displayName: WayScript
description: |
  WayScript is an Internal Developer Platform (IDP) that enables scalable, single click development environments. Connect your environments to New Relic in minutes.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: external-install.install
      requiresAccount: false
  fallback:
    link:
      url: https://wsxdocs.wayscript.com/managing-tools/integrations#new-relic
keywords:
  - wayscript
  - idp
  - internal developer platform
  - newrelic partner
  - featured
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
