id: kentik

displayName: Kentik Firehose

description: |
  This quickstart gives you visibility into data ingested via the Kentik Firehose. The data is sent to Kentik and enriched before being sent to New Relic.
  Deploying this quickstart gives insights into Network Flows, Network Synthetics, and performance telemetry associated with Kentik-monitored devices.
  For more information or support, please go to https://www.kentik.com/customer-care/

logo: logo.png

install:
  primary:
    nerdlet: nr1-install-newrelic.quickstart-installation-plan
    nerdletState:
      quickstart_id: a781c760-fd25-458f-a170-dae8c722b2ea
  requiresAccount: true
  secondary:
    link: https://kb.kentik.com/v0/Fc19.htm#Fc19-Firehose_Overview

keywords:
  - kentik
  - firehose
  - network
  - NPM
  - Synthetics
  - NetFlow
  - sFlow
  - JFlow
  - IPFIX
  - newrelic partner

categoryTerms:
  - newrelic partner
  - synthetics
  - network
