id: kentik
displayName: Kentik Firehose
description: |
  This quickstart gives you visibility into data ingested via the Kentik Firehose. The data is sent to Kentik and enriched before being sent to New Relic.
  Deploying this quickstart gives insights into Network Flows, Network Synthetics, and performance telemetry associated with Kentik-monitored devices.
  For more information or support, please go to https://www.kentik.com/customer-care/
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: a781c760-fd25-458f-a170-dae8c722b2ea
      requiresAccount: true
  fallback:
    link:
      url: https://kb.kentik.com/v0/Fc19.htm#Fc19-Firehose_Overview
keywords:
  - kentik
  - firehose
  - network
  - NPM
  - Synthetics
  - NetFlow
  - sFlow
  - JFlow
  - IPFIX
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
  - synthetics
  - network
