name: video-web-akamai
title: Video agent for Akamai player
description: Agent to monitor video applications using Akamai player.
summary: Agent to monitor video applications using Akamai player.
level: Community
authors:
  - New Relic Labs
keywords:
  - nrlabs
  - nrlabs-data
  - video
  - tracking
  - Akamai
documentation:
  - name: Video Akamai Installation Docs
    url: https://github.com/newrelic/video-akamai-js
    description: Agent to monitor video applications using Akamai player.
icon: icon.svg
logo: logo.svg