id: synthetics-endpoint-availability
displayName: Synthetics Endpoint Availability
description: Synthetic API tests are used to monitor your API endpoints. This can ensure that your app server works in addition to your website.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
icon: logo.svg
