id: 
name: customer-experience-quality-foundation 
title: Customer Experience Quality Foundation 

# Long-form description of the quickstart (required)
description: |
  Quality foundation helps you see what your user's perception of web performance is. It does this in two ways: (1) focuses on user experience metrics for availability, page load, and in-page actions (2) segments data by device type, region, and user journey 

  For more information view the [implementation guide](https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide)

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Focus on the user's experience of performance so you can optimize your site for satisfaction, retention, and conversion 

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Kim Hickey (New Relic)

# Keywords for filtering / searching criteria in the UI
keywords:
  - observability maturity
  - customer experience
  - quality foundation
  - browser
  - synthetics
  - ajax

documentation:
  - name: Implementation guide
    url: >-
     https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide 
    description:  |
        The implementation guide will show you how to implement customer experience quality foundation 

# Content / Design
logo: logo.png
website: https://www.newrelic.com
