id: perfmon
displayName: PerfMon
description: |
  Windows Performance Monitor is a toolkit that enables system performance data
  and analytics.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstart_id: db769025-d3a7-437b-896d-64f5a7a26cac
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/perfmon-open-source-integration
keywords:
  - infrastructure
  - windows
categoryTerms:
  - infrastructure
