name: 'import-data'
description: 'Import and validate observability packs'
author: 'New Relic'
inputs:
  nr-account-id:
    description: "Account id for new relic account"
    required: true
  github-token:
    description: "Token to use for authentication to GitHub APIs"
    required: true
  path-to-pack:
    description: "Path to the desire pack."
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
