id: 15ba39d9-f2de-4c4f-8ae5-255e5cf40d4d
slug: aws-kinesisanalytics
description: |-
  ## What is AWS Kinesis Analytics?

  Platform for streaming data on AWS, making it easy to load and analyze data in
  real time and build applications for specialized needs.


  ### Get started!

  Start monitoring AWS Kinesis Analytics by connecting Amazon Web Services (AWS) to New Relic!

  Check out our AWS Kinesis Analytics documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-kinesis-data-analytics-monitoring-integration/) to learn more about New Relic monitoring for AWS Kinesis Analytics.
summary: |-
  Monitor AWS Kinesis Analytics by connecting AWS to New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: AWS Kinesis Analytics
documentation:
  - name: AWS Kinesis Analytics installation docs
    description: |
      Monitor AWS Kinesis Analytics by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-kinesis-data-analytics-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - kinesis analytics

installPlans:
  - aws-cloudwatch-metric-streams
