id: e2ee8b6e-5c2a-11ed-9b6a-0242ac120002
slug: cockroach-database-newrelic
title: Cockroach Database-Newrelic

description: |
  [Cockroach Database ](https://www.cockroachlabs.com/docs/  ) CockroachDB is a distributed SQL database built on a transactional and strongly-consistent key-value store. It scales horizontally; survives disk, machine, rack, and even datacenter failures with minimal latency disruption and no manual intervention; supports strongly-consistent ACID transactions; and provides a familiar SQL API for structuring, manipulating, and querying data.

  Install this quickstart to access preconfigured Cockroach Database observability solutions based on Prometheus metrics that are available out-of-the-box

summary: |
   A curated dashboard based on Prometheus metrics which helps you understand the Cockroach Database performance of your k8s cluster. This quickstart is based on metrics sent to New Relic using Prometheus Agent or Prometheus Server.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Gulab Sidhwani

# Keywords for filtering / searching criteria in the UI
keywords:
  - Cockroach 
  - Database
  - kubernetes
  - k8s
  - prometheus
  - remote-write
  - sql

installPlans:
  - setup-prometheus
  - setup-prometheus-agent-mode

# Documentation references
documentation:
  - name: Prometheus installation docs
    description: |
     Use Prometheus remote_write or Prometheus Agent
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic
  - name: Cockroach Database Prometheus Integration
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/cockroach-db-integration
    description: Cockroach Database Prometheus Integration Documentation

icon: logo.png
website: https://www.cockroachlabs.com/docs/

dashboards:
  - cockroach-db

alertPolicies:
  - cockroach-db