# Name of the quickstart (required)
name: Gigamon-NewRelic

# Displayed in the UI (required)
title: Gigamon Quickstart

# Long-form description of the quickstart (required)
description: |
  Gigamon Cloud Suite enables collection of network traffic from every instance across the entire cloud solution. Customers can then choose to either centralize the traffic for network metadata generation for New Relic or choose to do so in a distributed fashion. 

  This integration provides a way to collect metadata of over 5,000 network traffic-related attributes and export that to New Relic Dashboard for holistic overview of cloud environment, and a much deeper level of security-related inspection.


# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Gigamon helps the world’s leading organizations run fast, stay secure and innovate. We provide the industry’s first elastic visibility and analytics fabric, which closes the cloud visibility gap by enabling cloud tools to see the network and network tools to see the cloud. With visibility across their entire hybrid cloud network, organizations can improve customer experience, eliminate security blind spots, and reduce cost and complexity. Gigamon has been awarded over 90 technology patents and enjoys world-class customer satisfaction with more than 4,000 organizations, including over 80 percent of the Fortune 100 and hundreds of government and educational organizations worldwide.
 
  To try this integration in your environment please reach out to tme@gigamon.com. If you are not aware of Gigamon Cloud Suite please reach out to sales@gigamon.com. 

  ![Gigamon Cloud Suite Overview](/images/CloudSuiteOverview.jpeg "Gigamon Cloud Suite Overview")
  ![Screenshot of demo data](/images/AppIntelDashBoard.jpeg "Screenshot of demo data")
  ![The example shows SSL attributes available to be exported.](/images/MetaDataAttributes.jpeg "The example shows SSL attributes available to be exported")
  ![Sample dashboard created using AMI attributes from Gigamon](/images/AppIntelDashBoard.jpeg "Sample dashboard created using AMI attributes from Gigamon")

# Support level: New Relic | Verified | Community (required)
level: Verified 

# Authors of the quickstart (required)
authors:
  - Haider Jarral

# Keywords for filtering / searching criteria in the UI
keywords:
  - Gigamon
  - Gigamon Cloud Suite
  - Gigamon Integration
  - featured


# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - third-party-gigamon

documentation:
  - name: Gigamon Cloud Suite Installation
    url: https://www.gigamon.com/lp/free-trial/request-live-cloud-demo.html
    description: The link refers to setting up demo for Cloud Suite Solution required to deploy the NewRelic Integration.

# Content / Design
icon: icon.jpeg
logo: logo.png
website: https://www.gigamon.com
