id: inet-oracle-driver
displayName: Inet Oracle Driver (oranxo)
description: Java driver built by Inet for managing Oracle database servers.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent
icon: logo.png
