id: 986df593-98db-485b-8e8c-dd866fa28813
name: python
description: |
  ### Complete Quickstart for Python Monitoring

  Python monitoring provides visibility into all your applications to help identify and resolve performance issues. Track key transactions, monitor a dashboard for critical metrics, and trigger alerts whenever an error or problem is detected before it impacts users.

  The Python dashboard enables development teams to dive deep into performance metrics to inspect database query traces, code-level transaction traces, and error traces.

  ### Why Monitoring Python Is so Important

  Python monitoring agents enable developers to troubleshoot application and endpoint issues, identify specific dependencies, and meet service level agreements. 

  Development teams can view detailed stack traces of sampled threads and extend performance monitoring to collect and analyze business data in a dashboard. This approach helps teams make data-driven decisions and enhance user experiences.

  ### What's Included in this Quickstart?

  New Relic's Python monitoring quickstart boasts instant full-stack observability out-of-the-box. This quickstart includes flexible options for custom instrumentation and APIs. There are multiple options to customize the data used by Python apps.

  ### New Relic Python Quickstart Features

  New Relic's Python process monitor quickstart offers:
  - Alerts (Adpex score, CPU utilization, transaction error)
  - Dashboards (most popular transactions, average transaction duration today compared with that for the previous week, Adpex score comparisons, and more) 
  - Monitor scripts and functions
  - Monitor WSGI web transactions

  ### New Relic - The Complete Python Performance Monitoring Tool

  New Relic's Python agent helps developers measure time-based values like connections per minute. It allows teams to capture discrete events with key-value attributes attached to them and analyze and query data.

  In addition to the above, New Relic's Python agent includes:
  - Browser monitoring
  - Browser and Django templates
  - Cross application tracing
  - Custom metrics
  - Event loop diagnostics
  - Message queues
  - Runtime metrics

  New Relic's instant observability quickstart helps Python developers minimize complexity and boost efficiency through enhanced visibility in a Python data dashboard. 

summary: |
  New Relic's instant observability quickstart boasts alerts, event loop diagnostics,
  and multiple customizable dashboards to detect and resolve issues before they impact end-users.
icon: icon.svg
logo: logo.svg
level: New Relic
authors:
  - New Relic
  - Emil Hammerstrand
title: Python
documentation:
  - name: Python installation docs
    description: |
      Python is an interpreted, high-level and general-purpose programming
      language.
    url: >-
      https://docs.newrelic.com/docs/agents/python-agent/getting-started/compatibility-requirements-python-agent
keywords:
  - apm
  - python
  - language agent

installPlans:
  - setup-python-agent
