# Name of the quickstart (required)
name: sendgrid-quickstart

# Displayed in the UI (required)
title: SendGrid Events

# Long-form description of the quickstart (required)
description: |
  SendGrid provides a cloud-based service that assists businesses with email delivery. This quickstart allows you to visualize status of email delivery. This requires you to send SendGrid events to New Relic someway. If you already send the events to AWS S3 by using SendGrid Event Webhook, they can be transferred to New Relic by using NewRelic-log-ingestion-s3.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Visualizing SendGrid events

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Kota Saito

# Keywords for filtering / searching criteria in the UI
keywords:
  - sendgrid
  - log

documentation:
  - name: SendGrid Getting started with the Event Webhook
    url: https://docs.sendgrid.com/for-developers/tracking-events/getting-started-event-webhook
    description: Description about how to send SendGrid Events via Webhook

  - name: AWS Lambda for sending logs from S3
    url: https://docs.newrelic.com/jp/docs/logs/forward-logs/aws-lambda-sending-logs-s3/
    description: Description about how to send logs stored in AWS S3 to New Relic

# Content / Design
logo: logo.png
website: https://sendgrid.com/
