# Name of the pack
name: MySQL / MariaDB

# Support level
level: New Relic

# Design
logo: logo.png
website: https://en.wikipedia.org/wiki/MySQL

# Authors of the quickstart
authors:
  - New Relic

# Instrumentation
instrumentation:
  - type: newrelic-infra-ohi
    name: mysql
