id: collectd
displayName: Collectd
description: |
  ## What is CollectD?

  Unix daemon for gathering and storing performance data across application and network infrastructure.

  ## Get started!

  New Relic's CollectD integration lets you easily get CollectD-format data into New Relic.
  Follow [the documentation](https://docs.newrelic.com/docs/integrations/host-integrations/open-source-host-integrations-list/collectd-open-source-integration) to get started!
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstart_id: b0ba29c2-be55-4da2-bf24-f8cc3c27715c
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/integrations/host-integrations/open-source-host-integrations-list/collectd-open-source-integration
keywords:
  - infrastructure
  - open source monitoring
categoryTerms:
  - open source monitoring
  - infrastructure
