

slug: ansible-automation-controller
description: |
  ## Why monitor Ansible Automation Controller?
  An ideal Ansible Automation Controller performance monitor must offer comprehensive and actionable information that software developers need to troubleshoot an application successfully. Some key components are:

  - Track the efficiency of business transactions starting using the Ansible Automation Controller server.
  - Use deep diagnostics to analyze and fix issues with application performance.
  - Drill down to the Ansible Automation Controller and the associated application components.
  - Detects faults to reduce application downtime.
  - Compare the performance of your Ansible Automation Controller servers.
  
  ## Comprehensive monitoring quickstart for Ansible Automation Controller
  
  New Relic's Ansible Automation Controller monitoring quickstart boasts instant full-stack observability out-of-the-box:

  - High value alerts for your Ansible Automation Controller (errors,usage metrics and Awx).
  - Easy to use performance monitoring dashboards (most successful transactions, average transaction duration today compared with that for the previous week, Awx organization comparisons, and more).
  - Custom alerts that proactively inform developers about the status of their Ansible Automation Controller servers.

  
summary: |
  The Ansible Automation Controller integration will enable you to monitor and analyze your Ansible Automation Controller infrastructure.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Ansible Automation Controller
documentation:
  - name: Ansible Automation Controller integration documentation
    description: |
      The Ansible Automation Controller integration will enable you to monitor and analyze your Ansible Automation Controller infrastructure.
    url: >-
      https://docs.newrelic.com/
keywords:
  - ansible automation platform
  - ansible tower
  - ansiblr automation controller
installPlans:
  - ansible-automation-controller
dashboards:
  - ansible-automation-controller
alertPolicies:
  - ansible-automation-controller
