id: 986df593-98db-485b-8e8c-dd866fa28813
name: python
description: Python is an interpreted, high-level and general-purpose programming language.
summary: Python is an interpreted, high-level and general-purpose programming language.
icon: icon.svg
logo: logo.svg
level: New Relic
authors:
  - New Relic
  - Emil Hammerstrand
title: Python
documentation:
  - name: Python installation docs
    description: |
      Python is an interpreted, high-level and general-purpose programming
      language.
    url: >-
      https://docs.newrelic.com/docs/agents/python-agent/getting-started/compatibility-requirements-python-agent
keywords:
  - apm
  - python
  - language agent

installPlans:
  - setup-python-agent
