id: network-syslog
displayName: Network Syslog
description: |
  Install NPM for syslog collection using a simple Docker container.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 478be4d3-134a-4738-995a-7bbe020edcad
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring/
keywords:
  - npm
  - network
  - networking
  - logging
  - ktranslate
  - kentik
  - infrastructure
  - newrelic partner
categoryTerms:
  - newrelic partner

