id: 289983fe-378e-4690-9302-2490e2afe11c

# Name of the pack
name: Redis

# Description of the pack
description: |+
  # A Complete Redis Monitoring System
  ## Monitoring Redis
  Redis is one of the most performant databases available to developers. It operates in-memory and consequently achieves I/O times orders of magnitude faster than traditional database systems. It can be used as a lightweight, distributed queue and also integrates useful features such as a pub/sub notification system.

  Redis is popular in the gaming, IoT, and mobile industries due to its easy onboarding and blazing-fast performance. It includes several data structures which make it ready to use right out of the box.

  New Relic provides a Redis dashboard which allows you to monitor your Redis instances.

  ## New Relic - A Perfect Tool to Monitor Redis
  Redis is known for its speed, so ensuring that it stays operating at peak performance is paramount. Slowdowns can lead to a compromised user experience or even a complete application failure.

  Monitoring Redis is a passive process, but the New Relic tool provides actionable insights into the health of a Redis system. In short, New Relic is more than just a monitor. It supports custom charts and custom queries using data from New Relic Insights, and pre-built dashboards are available for those who don’t need custom configurations. All critical performance and health metrics are monitored.

  ## New Relic Redis Kit Features
  - Overview Snapshot (# masters, # slaves) + charts with commands/sec and commands/sec by node
  - Charts showing connected clients, connected clients by node, changes since last save by node, expired keys/second by node, memory used by node, and blocked clients.
  - Charts showing keyspace hit ratio by node, evicted keys/second by node, input bytes/second by node, network I/O per second, and output bytes / second by node.

  ## Value of the Redis Pack
  The Redis Quickstart provides a visual snapshot of all the key health information related to your Redis nodes and clusters. Monitoring is made easy via the clear, color-coded dashboard which showcases memory usage, network I/O, node health, and much more.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://redis.io/

# Authors of the pack
authors:
  - New Relic
  - Jakub Kotkowiak

documentation:
  - name: Redis
    description: >-
      Open source, key-value data structure store for use as a database, cache, and message broker with wide protocol and dataset support.
    url: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration/

installPlans:
  - infra-agent-targeted
  - redis-integration
keywords:
  - infrastructure
  - database

