id: netlify-builds
displayName: Netlify Builds
description: |
  Netlify is an all-in-one platform for automating modern web projects. Replace your hosting infrastructure, continuous integration, and deployment pipeline with a single workflow. Integrate dynamic functionality like serverless functions, user authentication, and form handling as your projects grow.
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 5861d7f5-26c0-43ad-bda8-c893c4b27b25
      requiresAccount: true
  fallback:
    link:
      url: https://www.npmjs.com/package/@newrelic/netlify-plugin#installation
keywords:
  - infrastructure
  - automation
  - Netlify
  - Jamstack
  - RUM
  - browser agent
  - continuous integration
  - continuous deployment
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
  - infrastructure
  - browser agent
