name: video-web-jwplayer
title: Video agent for JWPlayer
description: Agent to monitor video applications using JWPlayer.
summary: Agent to monitor video applications using JWPlayer.
level: Community
authors:
  - New Relic
keywords:
  - nrlabs
  - nrlabs-data
  - video
  - tracking
  - Chromecast
documentation:
  - name: Video JWPlayer Installation Docs
    url: https://github.com/newrelic/video-jwplayer-js
    description: Agent to monitor video applications using JWPlayer.
icon: icon.svg
logo: logo.svg