
# Name of the pack
name: Couchbase

# Description of the pack
description: |+
  Official New Relic pack for Couchbase
  Use this pack together with the New Relic Couchbase On Host Integration to get insight into the performance of your Couchbase instances.

# Support level
level: New Relic

# Design
icon: icon.jpeg
logo: logo.png # When this is not set to a filepath or url, we look for logo.jpeg|jpg|png|gif?
website: https://www.couchbase.com/

# Authors of the quickstart
authors:
  - New Relic
  - Daniel Gola

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: couchbase
