id: contentsquare
displayName: Contentsquare
description: |
  Get more value from your investments in Contentsquare and New Relic by seeing
  how performance issues truly affect your customers' digital experience.

  Through this integration, access Contentsquare Session Replay links directly
  within New Relic. With this, Contentsquare shows you exactly what a user was
  doing before, during, and after an issue occurs, so that you can remediate
  issues quickly and with the complete picture. Dramatically reduce the
  time-to-repair of system errors by linking to your impacted users' exact
  session replays.

  - **Reduce time-to-recovery**

    By integrating Contentsquare with your New Relic, you can provide your
    engineering team with all of the necessary technical and behavioral data
    needed to identify the root cause of an issue without having to spend cycles
    trying to recreate the issue.


  - **Reduce time-to-recovery**

    Combine the technical data from New Relic with the behavioral data surfaced
    from Contentsquare to uncover and prioritize the issues that have the
    greatest impact on your revenue and customer experience metrics.
icon: logo.png
install:
  primary:
    link:
      url: https://uxanalyser.zendesk.com/hc/en-gb/articles/4408893503122-New-Relic
keywords:
  - Behavioural Analytics
  - Customer Experience
  - Digital Experience
  - User Experience
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
