id: 980ab07a-3483-4b44-bbac-ed9c0a9a41a1
slug: jenkins
title: Jenkins
description: |-
  ## What is Jenkins?

  The leading open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.

  ### Get started!

  Start monitoring Jenkins jobs and pipeline executions in New Relic!

  Check out our Monitoring Jenkins with OpenTelemetry and New Relic documentation to instrument your Jenkins instance with the OpenTelemetry plugin for Jenkins.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot/) to learn more about New Relic monitoring for Jenkins.
summary: |
  Monitor Jenkins with the OpenTelemetry plugin in New Relic.
level: Community
authors:
  - New Relic
  - Peter Nguyen
keywords:
  - jenkins
  - opentelemetry
  - otel
  - pipelines
  - newrelic partner
  - NR1_addData
  - NR1_sys
installPlans:
  - third-party-jenkins-integration
dataSourceIds:
  - otel-jenkins-integration
dashboards:
  - jenkins
documentation:
  - name: Set up Jenkins OpenTelemetry Plugin
    url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/jenkins/monitoring-jenkins-ot/
    description: Monitor Jenkins with the OpenTelemetry plugin by visualizing jobs and pipeline executions as distributed traces.
icon: logo.svg
website: https://www.newrelic.com
