name: releaseiq

title: ReleaseIQ

description: |
  ## What's ReleaseIQ?

  ReleaseIQ is the Unified Enterprise DevOps Platform to Accelerate Software Delivery. ReleaseIQ is focused on solving the problems of multi-tool, team, and product release pipelines.
 
  For ReleaseIQ intergration with New Relic, you must have :
  - New Relic License to be configured in ReleaseIQ Platform.
  - Configure NewRelic in ReleaseIQ platform Observability tool settings.
  
  ReleaseIQ Features with New Relic tool
  - Custom Events : During pipeline execution for each step, events with all step information is sent to NewRelic. To enable this feature, need to configure notification to NewRelic in each step.
  - Deployment Verification : Deployments can be verified by NewRelic based on the newrelic policies configured in deploy step of a pipeline and based on the priority alerts will be sent back to ReleaseIQ platform. Progress of Pipeline to subsequent steps will be based on deploymnet verififcation result.

summary: |
 
  Monitor ReleaseIQ Performance with New Relic's ReleaseIQ Agent.

level: Community


authors:
  - ReleaseIQ
  - Hemala Devanan

keywords:
  - releaseiq
  - integration
  - devops
  - newrelic partner


logo: logo.png
website: https://www.releaseiq.io/