id: b038e759-bf74-4353-9273-c66e86b25ebe
slug: blazor-server

description: |
  ## Comprehensive monitoring for Blazor Server
  As you probably know, Microsoft developed Blazor Server to build web UI components. As a feature of ASP.NET Core, our Blazor Server integration with the .NET APM agent lets you monitor your apps with our dashboards right out of the box.

  ## Why monitor your Blazor Server?
  There are a few strong arguments in favour of using Blazor Server:

  - Monitoring the Higher Letency and Slower Application.
  - Using New Relic .NET APM agent capture the Total transactions, Failed transactions, Active and Inactive connections.
  - Monitoring the application Performance, Errors and Apdex.
  - Near-native performance.
  - Debugging and tooling.

  ## What’s included?
  Get these Blazor Server monitoring features out of the box with New Relic:
  - Understand the health of your system with dashboards that show throughput and error rate data, logs, transaction time, Apdex score, and more. 
  - Get alerts when your application suffers critical failures and errors.
  - Monitor scripts and functions.
  - Monitor web transactions.
summary: | 
  Instrument and monitor your Blazor Server application with our .NET APM agent. Analyze your performance data right out of the box.
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Blazor Server
documentation:
  - name: Blazor Server installation docs
    description: |
      Our .NET APM agent can be used to instrument and monitor your Blazor Server application. Perform an immediate analysis of your performance statistics. 
    url: >- 
      https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework/#technologies
keywords:  

  - dotnet
  - .net
  - blazor

  - blazor server
installPlans:
  - blazor-server
dashboards:
  - blazor-server
alertPolicies:
  - blazor-server
