id: gigamon-appinsights
displayName: Gigamon Application Insights
description: |
  Gigamon Application Intelligence gives NetOps, CloudOps, and security teams full visibility into applications running in datacenters and public clouds. Therefore, you can maintain consistently strong security across your environment plus get to the root causes of vulnerabilities and performance bottlenecks.
icon: logo.png
install:
  primary:
    link:
      url: https://www.gigamon.com/partners/technology-partners.html#new-relic
keywords:
  - Gigamon
  - Gigamon Application Intelligence
  - Gigamon Integration
  - featured
  - security
  - packet capture
  - network
