slug: aws-kinesisanalytics
description: |-
  ## What is Amazon Kinesis Data Analytics?

  Platform for streaming data on AWS, making it easy to load and analyze data in
  real time and build applications for specialized needs.


  ### Get started!

  Start monitoring Amazon Kinesis Data Analytics by connecting Amazon Web Services (AWS) to New Relic!

  Check out our Amazon Kinesis Data Analytics documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

  ### More info

  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-kinesis-data-analytics-monitoring-integration/) to learn more about New Relic monitoring for Amazon Kinesis Data Analytics.
summary: |-
  Monitor Amazon Kinesis Data Analytics by connecting AWS to New Relic
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: Amazon Kinesis Data Analytics
documentation:
  - name: Amazon Kinesis Data Analytics installation docs
    description: |
      Monitor Amazon Kinesis Data Analytics by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-kinesis-data-analytics-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - kinesis analytics
dashboards:
  - amazon-kinesis-data-analytics
installPlans:
  - aws-cloudwatch-metric-streams
