id: audit-events-analysis
displayName: New Relic Audit
description: Dashboard to analyse the New Relic Audit events
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/data-apis/understand-data/event-data/query-account-audit-logs-nrauditevent/
icon: logo.svg
