id: third-party-netlify-logs
name: Netlify Logs
title: Netlify Logs quickstart
description: |
  Netlify is an all-in-one platform for automating modern web projects. Replace your hosting infrastructure, continuous integration, and deployment pipeline with a single workflow. Use this quickstart to quickly parse traffic and function logs from Netlify into meaningful metrics in New Relic.

target:
  type: integration
  destination: cloud

install:
  mode: link
  destination:
    url: https://docs.netlify.com/monitor-sites/log-drains/
