id: setup-prometheus-agent-mode
name: Prometheus Agent
title: Prometheus Agent
description: |
  Using the Prometheus Agent, you can easily spin up a Prometheus Server running in Agent mode forwarding the metrics to the New Relic Remote Write Endpoint.

target:
  type: integration
  destination: kubernetes

install:
  mode: link
  destination:
    url: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/install-prometheus-agent
