# Schema: link-to-schema-definition
version: 1
rules:
  ################
  # metadata
  ################
  name:
    type: text
    limit: 100
  level:
    type: enum
    values:
      - New Relic
      - Verified
      - Community
  authors:
    type: list(string)
    # limit: 10
  instrumentation:
    type: list(object)
    values:
      name:
        type: text
      type:
        type: text

  ################
  # Content
  ################
  title:
    type: text
    limit: 60
  short-description:
    type: text
    limit: 120
  full-description:
    type: text
    limit: 2000
  thumbnail:
    type: image
    format: { jpg|png }
    size: 4 # MB
    limit: 1
    aspect: 1.5
    width: 800
    height: 1600
  screenshots:
    type: image
    format: { jpg|png }
    size: 4 # MB
    limit: 6
    aspect: 1.5
    width: 800
    height: 1600
  icon:
    type: image
    format: { jpg|png }
    size: 4 # MB
    limit: 1
    aspect: 1.5
    width: 800
    height: 1600
  logo:
    type: image
    format: { jpg|png|svg }
    size: 4 # MB
    limit: 1
    aspect: 1.5
    width: 800
    height: 1600
  children:
    type: object
    value:
      title:
      description:
      screenshots:
  contributors:
    type: object
    value:
      github-username:
      profile-link:
      avatar-link:
