id: network-flow-devices
displayName: Network Flow Devices
description: |
  Set up your network devices so they send network data to New Relic One.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 6d275d10-9aaf-4351-b556-0174fca3ffca
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring
keywords:
  - npm
  - network
  - networking
  - flow
  - netflow
  - sflow
  - ipfix
  - jflow
  - ktranslate
  - kentik
  - infrastructure
  - newrelic partner
categoryTerms:
  - newrelic partner


