id: network-routers-and-switches
displayName: Network Routers and Switches
description: |
  The Network Routers and Switches datasource provides a dashboard that gives you a holistic view of the interface traffic across all of the routers and switches in your network.
  Use this datasource together with New Relic's Network Performance Monitoring (NPM) feature to visualize anomalies and/or bottlenecks in your network.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 8d843fc7-ffcf-489a-93b1-c8499cdd16ec
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring/
keywords:
  - npm
  - network
  - networking
  - router
  - switch
  - snmp
  - ktranslate
  - kentik
  - infrastructure
  - newrelic partner
categoryTerms:
  - newrelic partner

