id: activemq
displayName: ActiveMQ
description: Monitor the performance metrics of your Apache ActiveMQ instances in real-time with New Relic APM. New Relic detects your ActiveMQ metrics like queues, brokers, producers, consumers, garbage collection rate, heap memory usage and more.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-activemq
keywords:
  - activemq
  - jmx monitoring
  - apache
categoryTerms:
  - infrastructure
