id: network-data-ingest-and-cardinality 
displayName: Network Data Ingest and Cardinality
description: |
 The Network Data Ingest and Cardinality datasource provides a dashboard with several pages dedicated to analyzing both overall ingest and cardinality of telemetry from Network Performance Monitoring.
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 9ae44533-5dfa-4e8e-b72d-03b5b1bf9dba
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/network-performance-monitoring/get-started/npm-introduction/
keywords:
  - newrelic partner
  - npm
  - network
  - ingest
  - consumption
  - cardinality
  - ktranslate
  - kentik
  - featured
  - infrastructure
categoryTerms:
  - newrelic partner

