id: network-cisco-hardware
displayName: Cisco Hardware Sensor Dashboard
description: |
  Easily install a dashboard to see the status of Cisco hardware sensors.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/network-performance-monitoring/get-started/npm-introduction/
icon: logo.svg
