id: cloudflare
displayName: Cloudflare Network Logs
description: |
  ## About Cloudflare


  Cloudflare is an industry leading global network designed to make everything
  you connect to the Internet secure, private, fast, and reliable. Protect and
  accelerate external, public-facing web properties; secure your internal
  operations on a single global network; and build new applications on our
  serverless platform. Internet properties powered by Cloudflare have all web
  traffic routed through its intelligent global network, which gets smarter with
  every request.


  ## About this quickstart


  Cloudflare is on a mission to help build a better Internet. The Cloudflare
  quickstart will enable you to monitor and analyze web traffic metrics on a
  dashboard, integrating with New Relic’s database to provide an at-a-glance
  overview of the most important logs and metrics from your websites and
  applications.


  For more information check out our website at
  [cloudflare.com](https://www.cloudflare.com/)
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: fc2bb0ac-6622-43c6-8c1f-6a4c26ab5434
      requiresAccount: true
  fallback:
    link:
      url: https://docs.newrelic.com/docs/logs/forward-logs/cloudflare-logpush-forwarding
keywords:
  - cloudflare
  - logs
  - network
  - security
  - cdn
  - featured
  - newrelic partner
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
  - logs
  - network
