# Name of the quickstart
name: Catchpoint-Quickstart

# Displayed in the UI
title: Catchpoint Quickstart

# Long-form description of the quickstart 
description: |
  This Quickstart uses 
  
  
  point Test Data Webhook to send data to the New Relic Platform, this is accomplished by using New Relic’s Metrics API. 
  To complete this, we will rely on a third-party Google Cloud function to accept the data from Catchpoint API, process it in the desired format, and then push it to New Relic.
  With this we can visualize Catchpoint's digital experience data with New Relic’s Application Performance Monitoring (APM) data together.
   Dashboards:
  - Catchpoint-Overview dashboard: Overview of errors and request components of tests
  - Catchpoint-Recent Errors dashboard: Recent errors with test id, timestamp, node name and error code 
  - Catchpoint-Response Size: Monitor the average response size in MB
  - Catchpoint-Test Times: Test time of with respect to test ids.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  This Quickstart uses Catchpoint Test Data Webhook to send data to the New Relic Platform, this is accomplished by using New Relic’s Metrics API. 
  With this we can visualize Catchpoint's digital experience data with New Relic’s Application Performance Monitoring (APM) data together.
  Dashboards let you see the state of your monitored systems at a glance. 
  You can use them to monitor the performance of your Tests and Endpoints.
  They can display summary, errors, response sizes and test times related to catchpoint account.
  Anything that you monitor using Catchpoint can be summarized for you in a Dashboard.
   
# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Pavan Kumar

# Keywords for filtering / searching criteria in the UI
keywords:
  - METRICNAME
  - NODENAME
  - TESTID
  - TIMESTAMP


documentation:
  - name: Installation Docs
    url: docs.newrelic.com
    description: Description about this doc reference

# Content / Design
logo: logo.png
website: https://www.newrelic.com
