slug: openai
title: OpenAI Observability

description: |
  # description
  to go here

summary: |
  Summary here

icon: logo.svg

level: New Relic

authors:
  - New Relic

documentation:
  - name: Monitor OpenAI 
    description: |
      description of documentation
    url: >-
      link here

keywords:
  - featured
  - newrelic partner
    
installPlans:
  - setup-openai

dashboards:
  - openai
