slug: openai
title: OpenAI Observability

description: |
  PLACEHOLDER

summary: |
  PLACEHOLDER

icon: logo.svg

level: New Relic

authors:
  - New Relic

documentation:
  - name: Monitor OpenAI 
    description: |
      description of documentation
    url: >-
      https://github.com/newrelic/openai-api-monitoring

keywords:
  - featured
  - newrelic partner
    
installPlans:
  - setup-openai

dashboards:
  - openai
