id: test-data-source

displayName: Test Data Source

description: |
  test

install:
  primary:
    nerdlet: test.test-nerdlet
    nerdletState: 
      test_state: test
    requiresAccount: true
  secondary:
    link: https://newrelic.com


keywords:
  - test
  - keyword2

categoryTerms: 
  - test
  - term2
