id: synthetics-user-flow
displayName: Synthetics User Flow check
description: |
  Develop your own customised Synthetics check with a fully scriptable browser test.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/
icon: logo.svg
