id: gcp-infrastructure-monitoring
displayName: GCP Infrastructure monitoring
description: |
  GCP Infrastructure monitoring allows monitoring of various Google Cloud Platform services.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/get-started/connect-google-cloud-platform-services-new-relic/
