id: releaseiq
displayName: ReleaseIQ
description: |
  With ReleaseIQ quickstart, you get application performance information from ReleaseIQ platform in your New Relic dashboard.
icon: logo.png
install:
  primary:
    link:
      url: https://www.releaseiq.io/use-cases/new-relic/
keywords:
  - releaseiq
  - integration
  - releaseiq server
  - devops automation tool
  - newrelic partner
  - featured
categoryTerms:
  - newrelic partner
