name: ads-web-prebid
title: Agent for Prebid
description: Agent to monitor web applications using Prebid.
summary: Agent to monitor web applications using Prebid.
level: Community
authors:
  - New Relic Labs
keywords:
  - nrlabs
  - nrlabs-data
  - ads
  - tracking
  - Prebid
documentation:
  - name: Prebid agent Installation Docs
    url: https://github.com/newrelic/tracker-prebid-js
    description: Agent to monitor web applications using Prebid.
icon: icon.png
logo: logo.png