# Name of the quickstart (required)
name: nri-mssql-experimental
title: Microsoft SQL Server with Query Plan logging
description: |
  The original SQL Server nri with added Query Plan logging

  Dashboards:
  - SQL Overview: The SQL Overview tab displays Database/Log Space, Memory, Waits/Blocking, Blocked Processes
  - Query Performance: This tab includes the Query Plans widget

summary: |
  Send SQL Server Query Plans to the New Relic Logging API

logo: logo.svg
# Support level: New Relic | Verified | Community (required)
level: Community

website: https://cloud.google.com/apigee

keywords:
  - nrlabs
  - nrlabs-data
  - database
  - infrastructure

# Authors of the quickstart (required)
authors:
  - New Relic Labs

documentation:
  - name: Apigee Distributed Tracing documentation
    description: |
      Installation and configuration instructions
    url: https://github.com/newrelic-experimental/nri-mssql-experimental

