id: delphix

displayName: Delphix

description: |
  This Delphix quickstart allows you to get visibility into all your Delphix Virtualization platforms. Use this quickstart together with this [integration](https://github.com/delphix/dct-newrelic-integration)

logo: logo.png

install:
  primary:
    nerdlet: nr1-install-newrelic.quickstart-installation-plan
    nerdletState:
      quickstart_id: 98f77308-4ac3-4c55-bc56-eb9d12f52ab7
  requiresAccount: true
  secondary:
    link: https://github.com/delphix/dct-newrelic-integration

keywords:
  - delphix
  - newrelic partner
  - virtualization
  - featured

categoryTerms:
  - newrelic partner
