id: delphix
displayName: Delphix
description: |
  This Delphix quickstart allows you to get visibility into all your Delphix
  Virtualization platforms. Use this quickstart together with this
  [integration](https://github.com/delphix/dct-newrelic-integration)
icon: logo.png
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: 98f77308-4ac3-4c55-bc56-eb9d12f52ab7
      requiresAccount: true
  fallback:
    link:
      url: https://github.com/delphix/dct-newrelic-integration
keywords:
  - delphix
  - newrelic partner
  - virtualization
  - featured
  - NR1_addData
  - NR1_sys
categoryTerms:
  - newrelic partner
