id: d0e829a6-ede4-4933-9065-9f0c56f8aa7e # TODO(vivek): How to generate?
# Name of the quickstart (required)
name: truera

# Displayed in the UI
title: Truera

# Long-form description of the quickstart (required)
description: |
  TruEra provides best in class AI Quality diagnostics and monitoring solution. With this integration, TruEra and NewRelic users can go beyond standard accuracy, input and output drift monitoring by identifying consequential data drift, and other AI Quality diagnostics such as fairness, conceptual soundness and segment behavior. When combined with NewRelic’s comprehensive observability capabilities, MLOps teams can correlate signals throughout the ML lifecycle.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  TruEra provides best in class AI Quality diagnostics and monitoring solution. With this integration, TruEra and NewRelic users can go beyond standard accuracy, input and output drift monitoring by identifying consequential data drift, and other AI Quality diagnostics such as fairness, conceptual soundness and segment behavior. When combined with NewRelic’s comprehensive observability capabilities, MLOps teams can correlate signals throughout the ML lifecycle.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Truera

# Keywords for filtering / searching criteria in the UI
keywords:
  - mlops
  - ml
  - ai
  - machine-learning
  - machine learning
  - ml monitoring
  - machine learning monitoring
  - xai
  - explainable ai
  - explanability
  - fairness
  - truera

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - truera-mlops

documentation:
  - name: Truera Docs
    url: https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/mlops-integrations/truera-integration/
    description: Documentation on the workings of the Truera integration

# Content / Design
icon: icon.svg
logo: logo.svg
website: https://truera.com/
