# Name of the quickstart (required)
name: istio-quickstart

# Displayed in the UI (required)
title: Istio Quickstart

# Long-form description of the quickstart (required)
description: |
  The template quickstart allows you to get visibility into the performance and available of your example service and dependencies. Use this quickstart together with the mock up integrations.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  A short form description for this quickstart

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - New Relic

# Keywords for filtering / searching criteria in the UI
keywords:
  - istio
  - kubernetes
  - service
  - mesh
  - k8s

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - kubernetes-install

documentation:
  - name: Kubernetes/POMI installation docs
    description: |
      To view the Istio Quickstart, the Kubernetes New Relic integration with the Prometheus OpenMetrics Integration (POMI) must be installed prior.
    url: >-
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kubernetes-monitoring-integration
  - name: Prometheus OpenMetrics Intergration (POMI) installation docs
    description: |
      To view the Istio Quickstart, the Kubernetes New Relic integration with the Prometheus OpenMetrics Integration (POMI) must be installed prior.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic

# Content / Design
logo: logo.png
