id: squid-prometheus-integration-docs
displayName: Squid Prometheus Integration
description: |
  The New Relic Squid prometheus integration allows you to monitor your Squid cache managers
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-squid/
icon: logo.png
