
# Name of the pack
name: Redis

# Description of the pack
description: |+
  Official New Relic pack for Redis
  Use this pack together with the New Relic Redis On Host Integration to get insight into the performance of your Redis instances.

# Support level
level: New Relic

# Design
icon: icon.png
logo: logo.png
website: https://redis.io/

# Authors of the quickstart
authors:
  - New Relic
  - Jakub Kotkowiak

# Instrumentation (optional)
# This allows you to define which instrumentation is needed for your pack
# Any file in the instrumentation folder will automatically be picked up
instrumentation:
  - type: newrelic-infra-ohi
    name: redis
