slug: aws-alb
title: AWS ALB
description: |-
## What is AWS NLB/ALB?

Distributes incoming application traffic across multiple targets, such as EC2
instances, in multiple availability zones.


### Get started!

Start monitoring AWS ALB by connecting Amazon Web Services (AWS) to New Relic!

Check out our AWS ALB documentation to instrument your cloud service and manage the stability, scalability, and reliability of your systems with New Relic's infrastructure monitoring capabilities.

### More info

Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-albnlb-monitoring-integration/) to learn more about New Relic monitoring for AWS NLB/ALB.
summary: |- 
Monitor AWS ALB by connecting AWS to New Relic
level: New Relic
authors: New Relic
keywords:
  - aws
  - amazon web service
  - networking
documentation:
  name: AWS NLB/ALB installation docs
  url: https://docs.newrelic.com/docs/aws-alb-integration
  description: ''
icon: logo.svg
dashboards: 
  - aws-alb
  - aws-nlb
installPlans: 
  - aws-cloudwatch-metric-streams
