name: Move content PR to Project Board

on:
  pull_request_target:
    types: [opened]
    paths:
      - 'quickstarts/**'


env:
  GITHUB_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
  COLUMN_NAME: To do

jobs:
  move-pr-to-project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move PR to Project Board for triage
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") HEADER="Accept: application/vnd.github.inertia-preview+json" PR_ID=$(gh api -H "$HEADER" "repos/$REPOSITORY/pulls?state=open" --jq ".[] | select(.number == $PR_NUMBER).id") PROJECT=$(gh api -H "$HEADER" "repos/$REPOSITORY/projects" --jq ".[] | select(.id == $PROJECT_ID).id") COLUMN=$(gh api -H "$HEADER" "projects/$PROJECT/columns" --jq ".[] | select(.name == \"$COLUMN_NAME\").id") gh api -H "$HEADER" -X POST "projects/columns/$COLUMN/cards" -f content_type='PullRequest' -F content_id="$PR_ID"
